import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
import {buildFallbackPlan,providerStatus,summarizeCaptions} from './lib/provider-router.mjs';import {configured,translateExternal,validateExternal,summarizeExternal,transcribeExternal} from './lib/provider-adapters.mjs';import {claimCaptionRequest} from './lib/caption-idempotency.mjs';
import {createSpeechQualityQuota,speechQualityLabFlags,speechQualityProviderStatus,transcribeSpeechQualitySample} from './lib/speech-quality-lab-service.mjs';
const __dirname=path.dirname(fileURLToPath(import.meta.url)),publicDir=path.join(__dirname,'public'),frontendV4Dir=path.join(__dirname,'frontend-v4'),dataDir=process.env.DATA_DIR?path.resolve(process.env.DATA_DIR):path.join(__dirname,'data'),port=Number(process.env.PORT||4173);await fs.mkdir(dataDir,{recursive:true});
const names=['tasks','meetings','captions','events','users','sessions','consents','results'];const files=Object.fromEntries(names.map(k=>[k,path.join(dataDir,`${k}.json`)]));files.settings=path.join(dataDir,'settings.json');
const MAX_MEETING_PARTICIPANTS=8;
const defaultSettings={tenant_id:'demo-star45',translation:{green:90,yellow:70},providers:{stt:'browser',translation:'prototype',validator:'local',summary:'local'},fallback:{enabled:true},providerCatalog:{stt:['browser','openai','google','azure'],translation:['prototype','openai','gemini','deepl','google','azure'],validator:['local','openai','gemini'],summary:['local','openai','gemini']},privacy:{audioRetention:'delete_after_processing',analytics:false,adsPersonalization:false},integrations:{google:false,outlook:false,erp:false,obsidian:false},updated_at:new Date().toISOString()};
for(const [k,f] of Object.entries(files)){try{await fs.access(f)}catch{await fs.writeFile(f,k==='settings'?JSON.stringify(defaultSettings,null,2):'[]')}}
const JSON_RECOVERY_VERSION='v1-atomic',writeChains=new Map();function jsonSegments(raw){const out=[];let start=-1,depth=0,quoted=false,escaped=false;for(let i=0;i<raw.length;i++){const ch=raw[i];if(start<0){if(ch==='['||ch==='{'){start=i;depth=1}continue}if(quoted){if(escaped)escaped=false;else if(ch==='\\\\')escaped=true;else if(ch==='"')quoted=false;continue}if(ch==='"'){quoted=true;continue}if(ch==='['||ch==='{')depth++;else if(ch===']'||ch==='}'){depth--;if(depth===0){try{out.push(JSON.parse(raw.slice(start,i+1)))}catch{}start=-1}}}return out}async function atomicJsonWrite(f,d){const tmp=`${f}.tmp-${process.pid}-${crypto.randomBytes(4).toString('hex')}`;await fs.writeFile(tmp,JSON.stringify(d,null,2));await fs.rename(tmp,f)}async function recoverJson(f,raw,error){const values=jsonSegments(raw);if(!values.length)throw error;let recovered;if(values.every(Array.isArray)){const rows=new Map(),withoutId=[];for(const list of values)for(const row of list){if(!row||typeof row!=='object'||!row.id){withoutId.push(row);continue}const prev=rows.get(row.id),prevTime=Date.parse(prev?.updated_at||prev?.created_at||0)||Number(prev?.created_at)||0,nextTime=Date.parse(row.updated_at||row.created_at||0)||Number(row.created_at)||0;if(!prev||nextTime>=prevTime)rows.set(row.id,row)}recovered=[...rows.values(),...withoutId]}else recovered=values.at(-1);await fs.writeFile(`${f}.recovery-backup`,raw);await atomicJsonWrite(f,recovered);console.warn('JSON_RECOVERED',path.basename(f),values.length);return recovered}const rd=async f=>{const raw=await fs.readFile(f,'utf8');try{return JSON.parse(raw)}catch(error){return recoverJson(f,raw,error)}},wr=(f,d)=>{const run=()=>atomicJsonWrite(f,d),p=(writeChains.get(f)||Promise.resolve()).then(run,run);writeChains.set(f,p.catch(()=>{}));return p},mutate=(f,fn)=>{const run=async()=>{const current=await rd(f),result=await fn(current),data=result?.data??result;await atomicJsonWrite(f,data);return result?.value};const p=(writeChains.get(f)||Promise.resolve()).then(run,run);writeChains.set(f,p.catch(()=>{}));return p},now=()=>new Date().toISOString(),id=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const json=(res,s,b,h={})=>{res.writeHead(s,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...h});res.end(JSON.stringify(b))};const body=async req=>{let s='';for await(const c of req)s+=c;return s?JSON.parse(s):{}};const binaryBody=async(req,max=6*1024*1024)=>{const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>max)throw new Error('audio_too_large');chunks.push(chunk)}return Buffer.concat(chunks)};
const cookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));const hp=(p,s=crypto.randomBytes(16).toString('hex'))=>({salt:s,hash:crypto.pbkdf2Sync(p,s,120000,32,'sha256').toString('hex')});
async function me(req){const sid=cookies(req).voiceflow_session;if(!sid)return null;const s=(await rd(files.sessions)).find(x=>x.id===sid&&Date.parse(x.expires_at)>Date.now());if(!s)return null;return (await rd(files.users)).find(x=>x.id===s.user_id&&!x.deleted_at)||null}const safe=u=>u&&({id:u.id,name:u.name,email:u.email,role:u.role,status:u.status,created_at:u.created_at});
async function emit(type,payload={}){const a=await rd(files.events),e={id:id('evt'),type,payload,created_at:now()};a.unshift(e);await wr(files.events,a.slice(0,2000));return e}
const known={'Giá này đã bao gồm phí vận chuyển.':{'ko-KR':'이 가격에는 운송비가 포함되어 있습니다.'},'Giá này chưa bao gồm VAT.':{'ko-KR':'이 가격에는 VAT가 포함되어 있지 않습니다.'},'배송은 다음 주 월요일부터 시작하겠습니다.':{'vi-VN':'Việc giao hàng sẽ bắt đầu từ thứ Hai tuần tới.'}};
const detect=t=>/[가-힣]/.test(t)?'ko-KR':/[ăâđêôơưàáảãạằắẳẵặầấẩẫậèéẻẽẹềếểễệìíỉĩịòóỏõọồốổỗộờớởỡợùúủũụừứửữựỳýỷỹỵ]/i.test(t)?'vi-VN':/[ぁ-んァ-ン]/.test(t)?'ja-JP':/[\u4e00-\u9fff]/.test(t)?'zh-CN':'en-US';
function localValidate(a,b){const nums=s=>String(s).match(/\d+(?:[.,]\d+)*/g)||[],na=nums(a),nb=nums(b),numbers=na.every(x=>nb.includes(x))?100:55;const same=String(a).trim()===String(b).trim();const negA=/안 |않|없|미포함|không|chưa|not |no /i.test(a),negB=/안 |않|없|미포함|không|chưa|not |no /i.test(b);const negation=negA===negB?100:40;let score=Math.round(numbers*.3+negation*.25+(same?35:95)*.45);const issues=[];if(same)issues.push('translation_unchanged');if(numbers<100)issues.push('number_mismatch');if(negation<100)issues.push('negation_mismatch');return{score,light:score>=90?'green':score>=70?'yellow':'red',components:{number:numbers,negation,semantic:same?35:95},issues}}
async function translate(text,target,settings){const preferred=settings.providers?.translation||'prototype',plan=buildFallbackPlan(settings),requested=[preferred,plan.translation?.id].filter(p=>p&&p!=='prototype'),candidates=[...requested,'openai','gemini','deepl','google','azure'].filter((x,i,a)=>x&&a.indexOf(x)===i),errors=[];for(const p of candidates){try{const out=await translateExternal(p,text,target);if(out&&String(out).trim()!==String(text).trim())return{provider:p,text:out,fallback:p!==preferred,errors}}catch(e){errors.push(`${p}:${e?.message||'error'}`)}}return{provider:'prototype',text:known[text]?.[target]||text,fallback:true,errors}}
async function validate(original,translated,source,target,settings){const local=localValidate(original,translated),preferred=settings.providers?.validator||'local';if(preferred==='local'||local.score>=95)return{provider:'local',...local};for(const p of [preferred,'openai','gemini']){try{const v=await validateExternal(p,original,translated,source,target);const score=Math.min(local.score,Number(v.score||70));return{provider:p,score,light:score>=90?'green':score>=70?'yellow':'red',components:{...local.components,semantic:v.semantic||score},issues:[...new Set([...(local.issues||[]),...(v.issues||[])])]}}catch{}}return{provider:'local',...local}}
function taskStruct(text=''){const o=text.match(/([가-힣A-Za-z0-9_-]{2,16})(?:에게|한테)/);return{id:id('tsk'),title:text.trim().slice(0,160)||'새 업무',owner:o?.[1]||'미지정',deadline:'',status:'todo',priority:/긴급|최우선/.test(text)?'high':'normal',created_at:now()}}
async function updateMeeting(mid,fn){return mutate(files.meetings,a=>{const i=a.findIndex(x=>x.id===mid);if(i<0)return{data:a,value:null};a[i]=fn(a[i]);a[i].updated_at=now();return{data:a,value:a[i]}})}
async function finalize(mid){const caps=(await rd(files.captions)).filter(x=>x.meeting_id===mid),settings=await rd(files.settings),meeting=(await rd(files.meetings)).find(x=>x.id===mid)||null;let result=summarizeCaptions(caps),provider='local';if(caps.some(c=>String(c.text||'').trim()))for(const p of [settings.providers?.summary,settings.providers?.translation,'openai','gemini'].filter(Boolean)){if(p==='local'||p==='prototype')continue;try{const ext=await summarizeExternal(p,caps);if(ext&&String(ext.summary||'').trim()){result={...result,...ext,source_count:caps.length};provider=p;break}}catch{}}const primaryLanguage=meeting?.language||meeting?.participants?.[0]?.language||'ko-KR';result.localized_results={...(result.localized_results||{}),[primaryLanguage]:{summary:result.summary,decisions:result.decisions||[],risks:result.risks||[],actions:result.actions||[],source_count:caps.length}};const endedAt=now(),startedAt=meeting?.created_at||endedAt,participants=(meeting?.participants||[]).map(x=>({peer_id:x.peer_id||'',name:x.name||'참여자',language:x.language||''}));const row={id:id('res'),meeting_id:mid,provider,...result,started_at:startedAt,ended_at:endedAt,duration_seconds:Math.max(0,Math.round((Date.parse(endedAt)-Date.parse(startedAt))/1000)),participants,created_at:endedAt};const a=await rd(files.results),i=a.findIndex(x=>x.meeting_id===mid);if(i>=0)a[i]=row;else a.unshift(row);await wr(files.results,a.slice(0,1000));await updateMeeting(mid,m=>({...m,status:'ended',ended_at:endedAt,result_id:row.id}));await emit('meeting.finalized',{meeting_id:mid,result_id:row.id});return row}
async function rtcConfig(){let cfg={};try{cfg=JSON.parse(await fs.readFile(process.env.TURN_SECRET_FILE||path.join(dataDir,'turn-secret.json'),'utf8'))}catch{}const ttl=Math.max(300,Math.min(86400,Number(cfg.ttl_seconds||3600))),expires=Math.floor(Date.now()/1000)+ttl,username=`${expires}:voiceflow`,secret=String(cfg.secret||'');const urls=Array.isArray(cfg.urls)&&cfg.urls.length?cfg.urls:['stun:voice.star45.net:3478'];const iceServers=[{urls:[urls.find(x=>String(x).startsWith('stun:'))||'stun:voice.star45.net:3478']}];if(secret){const turnUrls=urls.filter(x=>String(x).startsWith('turn:')||String(x).startsWith('turns:'));if(turnUrls.length)iceServers.push({urls:turnUrls,username,credential:crypto.createHmac('sha1',secret).update(username).digest('base64')})}return{iceServers,ttl_seconds:ttl,relay_ready:!!secret}}
function serveText(res,title,text){const h=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${title}</title><body style="font-family:system-ui;max-width:760px;margin:40px auto;padding:20px"><h1>${title}</h1><p style="line-height:1.8">${text}</p><p><a href="/">VoiceFlow로 돌아가기</a></p></body></html>`;res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(h)}
const V4_MOBILE_ENABLED=process.env.VOICEFLOW_V4_MOBILE_ENABLED==='1';
const V4_LOCAL_STT_ENABLED=process.env.VOICEFLOW_V4_LOCAL_STT_ENABLED==='1';
const V4_SPEECH_QUALITY_LAB_ENABLED=speechQualityLabFlags(process.env).labEnabled;
const speechQualityQuota=createSpeechQualityQuota({limit:Number(process.env.VOICEFLOW_SPEECH_QUALITY_HOURLY_LIMIT||30)});
const V4_MOBILE_TYPES=Object.freeze({'.html':'text/html; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8'});
async function serveV4MobileAsset(pathname,res){
  if(!V4_MOBILE_ENABLED)return json(res,404,{ok:false,error:'v4_mobile_disabled'});
  let file='';
  if(pathname==='/v4/mobile'||pathname==='/v4/mobile/'){
    file=path.join(frontendV4Dir,'apps/mobile-pwa/index.html');
  }else{
    const mobile=pathname.match(/^\/v4\/mobile\/(app\.mjs|styles\.css)$/);
    const shared=pathname.match(/^\/v4\/mobile\/modules\/([A-Za-z0-9-]+)\/index\.mjs$/);
    if(mobile)file=path.join(frontendV4Dir,'apps/mobile-pwa',mobile[1]);
    else if(shared)file=path.join(frontendV4Dir,'packages',shared[1],'index.mjs');
    else return json(res,404,{ok:false,error:'v4_mobile_asset_not_found'});
  }
  try{
    const data=await fs.readFile(file),type=V4_MOBILE_TYPES[path.extname(file)]||'application/octet-stream';
    res.writeHead(200,{'content-type':type,'cache-control':'no-store','x-voiceflow-v4':'mobile-phase2'});
    return res.end(data);
  }catch(error){
    if(error?.code==='ENOENT')return json(res,404,{ok:false,error:'v4_mobile_asset_not_found'});
    throw error;
  }
}
async function serveV4LocalSttAsset(pathname,res){
  if(!V4_LOCAL_STT_ENABLED)return json(res,404,{ok:false,error:'v4_local_stt_disabled'});
  let file='';
  if(pathname==='/v4/local-stt-test'||pathname==='/v4/local-stt-test/'){
    file=path.join(frontendV4Dir,'apps/mobile-local-stt-test/index.html');
  }else{
    const appAsset=pathname.match(/^\/v4\/local-stt-test\/(app\.mjs|styles\.css|local-whisper-worker\.mjs|local-sw\.js|manifest\.webmanifest)$/);
    const shared=pathname.match(/^\/v4\/local-stt-test\/modules\/([A-Za-z0-9-]+)\/index\.mjs$/);
    if(appAsset)file=path.join(frontendV4Dir,'apps/mobile-local-stt-test',appAsset[1]);
    else if(pathname==='/v4/local-stt-test/base.css')file=path.join(frontendV4Dir,'apps/mobile-pwa/styles.css');
    else if(shared)file=path.join(frontendV4Dir,'packages',shared[1],'index.mjs');
    else return json(res,404,{ok:false,error:'v4_local_stt_asset_not_found'});
  }
  try{
    const data=await fs.readFile(file),type=V4_MOBILE_TYPES[path.extname(file)]||'application/octet-stream';
    res.writeHead(200,{'content-type':type,'cache-control':'no-store','x-voiceflow-v4':'local-stt-pwa-canary-v1'});
    return res.end(data);
  }catch(error){
    if(error?.code==='ENOENT')return json(res,404,{ok:false,error:'v4_local_stt_asset_not_found'});
    throw error;
  }
}
async function serveV4SpeechQualityLabAsset(pathname,res){
  if(!V4_SPEECH_QUALITY_LAB_ENABLED)return json(res,404,{ok:false,error:'speech_quality_lab_disabled'});
  let file='';
  if(pathname==='/v4/speech-quality-lab'||pathname==='/v4/speech-quality-lab/'){
    file=path.join(frontendV4Dir,'apps/speech-quality-lab/index.html');
  }else{
    const appAsset=pathname.match(/^\/v4\/speech-quality-lab\/(app\.mjs|styles\.css|sw\.js|manifest\.webmanifest)$/);
    const shared=pathname.match(/^\/v4\/speech-quality-lab\/modules\/(speech-quality-evaluator)\/index\.mjs$/);
    if(appAsset)file=path.join(frontendV4Dir,'apps/speech-quality-lab',appAsset[1]);
    else if(shared)file=path.join(frontendV4Dir,'packages',shared[1],'index.mjs');
    else return json(res,404,{ok:false,error:'speech_quality_lab_asset_not_found'});
  }
  try{
    const data=await fs.readFile(file),type=V4_MOBILE_TYPES[path.extname(file)]||'application/octet-stream';
    res.writeHead(200,{'content-type':type,'cache-control':'no-store','x-voiceflow-v4':'speech-quality-lab-v1'});
    return res.end(data);
  }catch(error){
    if(error?.code==='ENOENT')return json(res,404,{ok:false,error:'speech_quality_lab_asset_not_found'});
    throw error;
  }
}
const ROOM_CORE_VERSION='v345-caption-revision-sync';
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS','access-control-allow-headers':'content-type,x-voice-client,x-voice-language,x-voice-audio-consent,x-voice-session-id,x-voice-utterance-id,x-voice-sequence,x-voice-audio-duration-ms'});return res.end()}
if(u.pathname==='/v4/mobile'||u.pathname.startsWith('/v4/mobile/'))return serveV4MobileAsset(u.pathname,res);
if(u.pathname==='/v4/local-stt-test'&&V4_LOCAL_STT_ENABLED){res.writeHead(308,{'location':`/v4/local-stt-test/${u.search}`,'cache-control':'no-store'});return res.end()}
if(u.pathname==='/v4/local-stt-test'||u.pathname.startsWith('/v4/local-stt-test/'))return serveV4LocalSttAsset(u.pathname,res);
if(u.pathname==='/v4/speech-quality-lab'&&V4_SPEECH_QUALITY_LAB_ENABLED){res.writeHead(308,{'location':`/v4/speech-quality-lab/${u.search}`,'cache-control':'no-store'});return res.end()}
if(u.pathname==='/v4/speech-quality-lab'||u.pathname.startsWith('/v4/speech-quality-lab/'))return serveV4SpeechQualityLabAsset(u.pathname,res);
if(String(req.headers['x-voice-client']||'')==='v4-local-stt-test'&&(u.pathname==='/api/v1/meetings'||u.pathname.startsWith('/api/v1/meetings/'))&&!await me(req))return json(res,401,{ok:false,error:'signup_consent_required'});
if(u.pathname==='/api/health')return json(res,200,{ok:true,service:'voiceflow',version:'2.0.0',features:['recording-first','audio-waveform','chat','optional-video-consent','captions','language-detection','translation-assurance','provider-router','automatic-fallback','meeting-results','auth','consent','member-admin','provider-admin','integration-status','pwa','webrtc-turn','room-regression-v344','atomic-json-recovery-v1']});
if(u.pathname==='/api/v1/webrtc/config'&&req.method==='GET')return json(res,200,{ok:true,data:await rtcConfig()});
if(u.pathname==='/api/v1/auth/register'&&req.method==='POST'){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim(),password=String(b.password||'');if(!email.includes('@')||name.length<2||password.length<8)return json(res,400,{ok:false,error:'invalid_input'});if(!b.termsAccepted||!b.privacyAccepted)return json(res,400,{ok:false,error:'consent_required'});const us=await rd(files.users);if(us.some(x=>x.email===email&&!x.deleted_at))return json(res,409,{ok:false,error:'email_exists'});const x=hp(password),user={id:id('usr'),name,email,passwordHash:x.hash,passwordSalt:x.salt,role:us.length?'member':'admin',status:'active',created_at:now()};us.push(user);await wr(files.users,us);const cs=await rd(files.consents);cs.push({id:id('cns'),user_id:user.id,terms:true,privacy:true,marketing:!!b.marketingAccepted,version:'2.0',created_at:now()});await wr(files.consents,cs);const sid=id('ses'),ss=await rd(files.sessions);ss.push({id:sid,user_id:user.id,created_at:now(),expires_at:new Date(Date.now()+14*864e5).toISOString()});await wr(files.sessions,ss);return json(res,201,{ok:true,user:safe(user)},{'set-cookie':`voiceflow_session=${sid}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=1209600`})}
if(u.pathname==='/api/v1/auth/login'&&req.method==='POST'){const b=await body(req),user=(await rd(files.users)).find(x=>x.email===String(b.email||'').trim().toLowerCase()&&!x.deleted_at);if(!user||user.status!=='active'||hp(String(b.password||''),user.passwordSalt).hash!==user.passwordHash)return json(res,401,{ok:false,error:'invalid_login'});const sid=id('ses'),ss=await rd(files.sessions);ss.push({id:sid,user_id:user.id,created_at:now(),expires_at:new Date(Date.now()+14*864e5).toISOString()});await wr(files.sessions,ss);return json(res,200,{ok:true,user:safe(user)},{'set-cookie':`voiceflow_session=${sid}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=1209600`})}
if(u.pathname==='/api/v1/auth/me')return json(res,200,{ok:true,user:safe(await me(req))});if(u.pathname==='/api/v1/auth/logout'&&req.method==='POST')return json(res,200,{ok:true},{'set-cookie':'voiceflow_session=; Path=/; HttpOnly; Secure; Max-Age=0; SameSite=Lax'});
if(u.pathname==='/api/v1/speech-quality/providers'&&req.method==='GET'){
  if(!V4_SPEECH_QUALITY_LAB_ENABLED)return json(res,404,{ok:false,error:'speech_quality_lab_disabled'});
  const user=await me(req);if(!user)return json(res,401,{ok:false,error:'login_required'});
  return json(res,200,{ok:true,data:{user:safe(user),providers:speechQualityProviderStatus(process.env)}});
}
const speechQualityTranscribe=u.pathname.match(/^\/api\/v1\/speech-quality\/transcribe\/([a-z0-9-]+)$/);
if(speechQualityTranscribe&&req.method==='POST'){
  if(!V4_SPEECH_QUALITY_LAB_ENABLED)return json(res,404,{ok:false,error:'speech_quality_lab_disabled'});
  if(String(req.headers['x-voice-client']||'')!=='v4-speech-quality-lab')return json(res,400,{ok:false,error:'speech_quality_client_required'});
  const user=await me(req);if(!user)return json(res,401,{ok:false,error:'login_required'});
  if(String(req.headers['x-voice-audio-consent']||'')!=='session')return json(res,403,{ok:false,error:'speech_audio_consent_required'});
  const mimeType=String(req.headers['content-type']||'').split(';')[0];if(!mimeType.startsWith('audio/'))return json(res,415,{ok:false,error:'audio_required'});
  const audio=await binaryBody(req,8*1024*1024);if(audio.length<800)return json(res,400,{ok:false,error:'audio_empty'});
  const quota=speechQualityQuota.claim(user.id);if(!quota.allowed)return json(res,429,{ok:false,error:'speech_quality_rate_limited',retry_after_ms:quota.retryAfterMs});
  try{
    const data=await transcribeSpeechQualitySample({
      providerId:speechQualityTranscribe[1],audio,mimeType,
      sourceLanguage:String(req.headers['x-voice-language']||'ko-KR'),
      sessionId:String(req.headers['x-voice-session-id']||''),
      utteranceId:String(req.headers['x-voice-utterance-id']||''),
      sequence:Number(req.headers['x-voice-sequence']||0),audioConsent:'session',
      audioDurationMs:Number(req.headers['x-voice-audio-duration-ms']||0),env:process.env,
    });
    return json(res,200,{ok:true,data},{'x-voiceflow-quota-remaining':String(quota.remaining)});
  }catch(error){
    if(error?.code==='speech_quality_provider_unknown')return json(res,404,{ok:false,error:error.code});
    if(error?.code==='speech_quality_provider_unavailable')return json(res,503,{ok:false,error:error.code,reason:error.reason});
    if(error instanceof TypeError||String(error?.code||'').startsWith('speech_'))return json(res,400,{ok:false,error:error.code||error.message});
    console.warn('SPEECH_QUALITY_PROVIDER_ERROR',speechQualityTranscribe[1],String(error?.code||'provider_failed'));
    return json(res,502,{ok:false,error:'speech_quality_provider_failed',provider:speechQualityTranscribe[1]});
  }
}
if(u.pathname==='/api/v1/account/delete'&&req.method==='POST'){const m=await me(req);if(!m)return json(res,401,{ok:false});const a=await rd(files.users),i=a.findIndex(x=>x.id===m.id);a[i]={...a[i],status:'deleted',deleted_at:now(),email:`deleted+${m.id}@invalid.local`,name:'Deleted User'};await wr(files.users,a);return json(res,200,{ok:true},{'set-cookie':'voiceflow_session=; Path=/; HttpOnly; Secure; Max-Age=0; SameSite=Lax'})}
if(u.pathname==='/api/v1/admin/settings'&&req.method==='GET')return json(res,200,{ok:true,data:await rd(files.settings)});if(u.pathname==='/api/v1/admin/settings'&&req.method==='PATCH'){const m=await me(req);if(!m||m.role!=='admin')return json(res,403,{ok:false,error:'forbidden'});const b=await body(req),s=await rd(files.settings),n={...s,...b,providers:{...s.providers,...(b.providers||{})},privacy:{...s.privacy,...(b.privacy||{})},integrations:{...s.integrations,...(b.integrations||{})},updated_at:now()};await wr(files.settings,n);return json(res,200,{ok:true,data:n})}
if(u.pathname==='/api/v1/admin/users'&&req.method==='GET'){const m=await me(req);if(!m||m.role!=='admin')return json(res,403,{ok:false});return json(res,200,{ok:true,data:(await rd(files.users)).filter(x=>!x.deleted_at).map(safe)})}
const adminUser=u.pathname.match(/^\/api\/v1\/admin\/users\/(usr_[A-Za-z0-9_]+)$/);if(adminUser&&req.method==='PATCH'){const m=await me(req);if(!m||m.role!=='admin')return json(res,403,{ok:false,error:'forbidden'});const b=await body(req),status=['active','suspended'].includes(b.status)?b.status:'';if(!status)return json(res,400,{ok:false,error:'invalid_status'});if(adminUser[1]===m.id&&status!=='active')return json(res,409,{ok:false,error:'self_admin_change_forbidden'});const a=await rd(files.users),i=a.findIndex(x=>x.id===adminUser[1]&&!x.deleted_at);if(i<0)return json(res,404,{ok:false,error:'user_not_found'});a[i]={...a[i],status,updated_at:now()};await wr(files.users,a);return json(res,200,{ok:true,data:safe(a[i])})}if(adminUser&&req.method==='DELETE'){const m=await me(req);if(!m||m.role!=='admin')return json(res,403,{ok:false,error:'forbidden'});if(adminUser[1]===m.id)return json(res,409,{ok:false,error:'self_delete_forbidden'});const a=await rd(files.users),i=a.findIndex(x=>x.id===adminUser[1]&&!x.deleted_at);if(i<0)return json(res,404,{ok:false,error:'user_not_found'});if(a[i].role==='admin'&&a.filter(x=>x.role==='admin'&&x.status==='active'&&!x.deleted_at).length<=1)return json(res,409,{ok:false,error:'last_admin_delete_forbidden'});const deletedAt=now();a[i]={...a[i],status:'deleted',deleted_at:deletedAt,email:`deleted+${a[i].id}@invalid.local`,name:'Deleted User'};await wr(files.users,a);const sessions=await rd(files.sessions);await wr(files.sessions,sessions.filter(x=>x.user_id!==a[i].id));await emit('admin.user.deleted',{user_id:a[i].id,deleted_by:m.id});return json(res,200,{ok:true,data:{id:a[i].id,deleted_at:deletedAt}})}
if(u.pathname==='/api/v1/users/directory'&&req.method==='GET'){const m=await me(req);if(!m)return json(res,401,{ok:false,error:'login_required'});const users=(await rd(files.users)).filter(x=>!x.deleted_at&&x.status!=='suspended').map(x=>({id:x.id,name:x.name,role:x.role||'member'}));return json(res,200,{ok:true,data:users})}
if(u.pathname==='/api/v1/admin/providers/status')return json(res,200,{ok:true,data:{catalog:providerStatus(),configured:configured(),plan:buildFallbackPlan(await rd(files.settings))}});
if(u.pathname==='/api/v1/admin/diagnostics')return json(res,200,{ok:true,data:{overall:88,providers:Object.entries(buildFallbackPlan(await rd(files.settings))).map(([id,p])=>({id,provider:p?.id||'none',status:p?'ok':'warning',score:p?.mode==='external'?94:82,recommend:p?.mode==='external'?'실사용 샘플 품질 측정 권장':'외부 Provider 키 연결 시 품질 향상 가능'})),checks:{api:true,storage:true,auth:true,meeting:true,captions:true,router:true}}});
if(u.pathname==='/api/v1/integrations/status')return json(res,200,{ok:true,data:{google:{configured:!!process.env.GOOGLE_CLIENT_ID},outlook:{configured:!!process.env.MS_CLIENT_ID},erp:{configured:!!process.env.ERP_API_BASE&&!!process.env.ERP_API_TOKEN},obsidian:{configured:!!process.env.OBSIDIAN_VAULT_PATH},webhooks:{configured:!!process.env.WEBHOOK_URL}}});
if(u.pathname==='/api/v1/tasks'&&req.method==='GET')return json(res,200,{ok:true,data:await rd(files.tasks)});if(u.pathname==='/api/v1/tasks'&&req.method==='POST'){const b=await body(req),a=await rd(files.tasks),t=taskStruct(b.text||b.title||'');a.unshift(t);await wr(files.tasks,a);return json(res,201,{ok:true,data:t})}
if(u.pathname==='/api/v1/meetings'&&req.method==='GET')return json(res,200,{ok:true,data:await rd(files.meetings)});if(u.pathname==='/api/v1/meetings'&&req.method==='POST'){const b=await body(req),a=await rd(files.meetings),demoTag=String(b.demo_tag||'').startsWith('demo-')?String(b.demo_tag).slice(0,80):'',m={id:id('mtg'),type:b.type==='client'?'client':'internal',title:b.title||'새 회의',status:'live',host_peer_id:b.peer_id||'',max_participants:MAX_MEETING_PARTICIPANTS,participants:b.peer_id?[{peer_id:b.peer_id,name:b.name||'Host',language:b.language||'ko-KR',joined_at:now()}]:[],signals:[],...(demoTag?{demo_tag:demoTag}:{}),created_at:now(),updated_at:now()};a.unshift(m);await wr(files.meetings,a);return json(res,201,{ok:true,data:m})}
if(u.pathname==='/api/v1/admin/demo-data'&&req.method==='DELETE'){const user=await me(req);if(!user||user.role!=='admin')return json(res,403,{ok:false,error:'admin_required'});const meetings=await rd(files.meetings),demoIds=new Set(meetings.filter(x=>String(x.demo_tag||'').startsWith('demo-')).map(x=>x.id));if(!demoIds.size)return json(res,200,{ok:true,data:{meetings:0,captions:0,results:0}});const captions=await rd(files.captions),results=await rd(files.results),keptMeetings=meetings.filter(x=>!demoIds.has(x.id)),keptCaptions=captions.filter(x=>!demoIds.has(x.meeting_id)),keptResults=results.filter(x=>!demoIds.has(x.meeting_id));await wr(files.meetings,keptMeetings);await wr(files.captions,keptCaptions);await wr(files.results,keptResults);await emit('admin.demo_data.reset',{deleted_by:user.id,meeting_count:meetings.length-keptMeetings.length,caption_count:captions.length-keptCaptions.length,result_count:results.length-keptResults.length});return json(res,200,{ok:true,data:{meetings:meetings.length-keptMeetings.length,captions:captions.length-keptCaptions.length,results:results.length-keptResults.length}})}
const meetingItem=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)$/);if(meetingItem&&req.method==='GET'){const m=(await rd(files.meetings)).find(x=>x.id===meetingItem[1]);return m?json(res,200,{ok:true,data:m}):json(res,404,{ok:false,error:'meeting_not_found'})}const join=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)\/join$/);if(join&&req.method==='POST'){const b=await body(req),joinedAt=now();let joinError='';const m=await updateMeeting(join[1],x=>{const current=Array.isArray(x.participants)?x.participants:[],alreadyJoined=current.some(p=>p.peer_id===b.peer_id);if(!alreadyJoined&&current.length>=MAX_MEETING_PARTICIPANTS){joinError='meeting_full';return x}const participant={peer_id:b.peer_id,name:b.name||'Guest',language:b.language||'ko-KR',joined_at:joinedAt},participants=[...current.filter(p=>p.peer_id!==b.peer_id),participant];if(alreadyJoined)return{...x,max_participants:MAX_MEETING_PARTICIPANTS,participants};const joinedSignal={id:id('sig'),from:'system',to:'*',type:'participant-joined',payload:{peer_id:participant.peer_id,name:participant.name,language:participant.language},created_at:Date.now()};return{...x,max_participants:MAX_MEETING_PARTICIPANTS,participants,signals:[...(x.signals||[]).slice(-199),joinedSignal]}});if(!m)return json(res,404,{ok:false,error:'meeting_not_found'});if(joinError)return json(res,409,{ok:false,error:joinError,max_participants:MAX_MEETING_PARTICIPANTS});return json(res,200,{ok:true,data:m})}
const sig=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)\/signals$/);if(sig&&req.method==='GET'){const m=(await rd(files.meetings)).find(x=>x.id===sig[1]);if(!m)return json(res,404,{ok:false});const peer=u.searchParams.get('peer'),since=Number(u.searchParams.get('since')||0);return json(res,200,{ok:true,data:(m.signals||[]).filter(s=>(!peer||s.to===peer||s.to==='*')&&s.created_at>since)})}if(sig&&req.method==='POST'){const b=await body(req),sg={id:id('sig'),from:b.from,to:b.to||'*',type:b.type,payload:b.payload||{},created_at:Date.now()};const m=await updateMeeting(sig[1],x=>({...x,signals:[...(x.signals||[]).slice(-199),sg]}));return m?json(res,201,{ok:true,data:sg}):json(res,404,{ok:false})}
const transcribe=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)\/transcribe$/);if(transcribe&&req.method==='POST'){const voiceClient=String(req.headers['x-voice-client']||'');if(voiceClient==='v4-local-stt-test'&&String(req.headers['x-voice-audio-consent']||'')!=='session')return json(res,403,{ok:false,error:'server_audio_consent_required'});const meeting=(await rd(files.meetings)).find(x=>x.id===transcribe[1]);if(!meeting)return json(res,404,{ok:false,error:'meeting_not_found'});const mime=String(req.headers['content-type']||'audio/webm').split(';')[0];if(!mime.startsWith('audio/'))return json(res,415,{ok:false,error:'audio_required'});const audio=await binaryBody(req);if(audio.length<800)return json(res,400,{ok:false,error:'audio_empty'});const language=String(req.headers['x-voice-language']||'ko-KR'),result=await transcribeExternal(audio,{language,mimeType:mime,useRuntimeRouting:['v4-mobile','v4-local-stt-test'].includes(voiceClient)}),text=typeof result==='string'?result:String(result?.text||''),target=String(req.headers['x-voice-target']||''),settings=await rd(files.settings);let translation='',translationProvider='';if(text&&target&&target!==language){const tr=await translate(text,target,settings);translation=tr.text;translationProvider=tr.provider}return json(res,200,{ok:true,text,provider:result?.provider||'unknown',model:result?.model||'',language,target,translation,translation_provider:translationProvider})}
const caps=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)\/captions$/);if(caps&&req.method==='GET'){const target=u.searchParams.get('target')||'ko-KR',since=Number(u.searchParams.get('since')||0),all=(await rd(files.captions)).filter(x=>x.meeting_id===caps[1]&&Math.max(Number(x.created_at)||0,Date.parse(x.updated_at||'')||0)>since),m=(await rd(files.meetings)).find(x=>x.id===caps[1]);for(const c of all){if(c.peer_id){const p=m?.participants?.find(x=>x.peer_id===c.peer_id);if(p?.language)c.participant_language=p.language}c.display_target=target}return json(res,200,{ok:true,data:all})}if(caps&&req.method==='POST'){const b=await body(req),settings=await rd(files.settings),source=b.detected_language||b.language||detect(b.text||''),clientId=String(b.client_id||'').trim(),m=(await rd(files.meetings)).find(x=>x.id===caps[1]),row={id:id('cap'),meeting_id:caps[1],...(clientId?{client_id:clientId}:{}),peer_id:b.peer_id||'',speaker:b.speaker||'',language:source,detected_language:source,text:b.text||'',translations:{},assurance:{},pending_translation:true,created_at:Date.now()},claim=await mutate(files.captions,a=>{const result=claimCaptionRequest(a,row);return{data:result.data,value:result}});if(claim.kind==='conflict')return json(res,409,{ok:false,error:'caption_idempotency_conflict',client_id:clientId});if(claim.kind==='replay')return json(res,claim.row.pending_translation?202:200,{ok:true,data:claim.row,replayed:true});try{const targets=[...new Set([b.target_language,...(m?.participants||[]).map(x=>x.language)].filter(x=>x&&x!==source))];if(!targets.length)targets.push(source==='ko-KR'?'vi-VN':'ko-KR');const translations={},assurance={};for(const t of targets){const tr=await translate(b.text||'',t,settings),v=await validate(b.text||'',tr.text,source,t,settings);translations[t]=tr.text;assurance[t]={...v,provider:v.provider,translation_provider:tr.provider,fallback:tr.fallback}}const complete={...row,translations,assurance,pending_translation:false,updated_at:now()};await mutate(files.captions,a=>{const index=a.findIndex(x=>x.id===row.id);if(index>=0)a[index]=complete;else a.push(complete);return{data:a.slice(-5000)}});return json(res,201,{ok:true,data:complete})}catch(error){if(clientId)await mutate(files.captions,a=>({data:a.filter(x=>x.id!==row.id)}));throw error}}const captionEditItem=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)\/captions\/(cap_[A-Za-z0-9_]+)$/);
if(captionEditItem&&req.method==='PATCH'){
  const b=await body(req),target=String(b.target||'').trim(),translation=String(b.translation||'').trim().slice(0,10000),correctedText=String(b.text||'').trim().slice(0,10000),peer=String(b.peer_id||''),user=await me(req),a=await rd(files.captions),i=a.findIndex(x=>x.id===captionEditItem[2]&&x.meeting_id===captionEditItem[1]);
  if(i<0)return json(res,404,{ok:false,error:'caption_not_found'});
  const meeting=(await rd(files.meetings)).find(x=>x.id===captionEditItem[1]),host=!!peer&&meeting?.host_peer_id===peer,own=!!peer&&a[i].peer_id===peer,admin=user?.role==='admin';
  if(!own&&!host&&!admin)return json(res,403,{ok:false,error:'caption_edit_forbidden'});
  if(correctedText){
    const settings=await rd(files.settings),source=a[i].detected_language||a[i].language||detect(correctedText),targets=[...new Set([target,...Object.keys(a[i].translations||{}),...(meeting?.participants||[]).map(x=>x.language)].filter(x=>x&&x!==source))],translations={...(a[i].translations||{})},assurance={...(a[i].assurance||{})};
    for(const t of targets){const tr=await translate(correctedText,t,settings),v=await validate(correctedText,tr.text,source,t,settings);translations[t]=tr.text;assurance[t]={...v,provider:v.provider,translation_provider:tr.provider,fallback:tr.fallback}}
    const current={...a[i]};delete current.translation;delete current.validation;
    a[i]={...current,text:correctedText,translations,assurance,text_feedback:{status:'corrected',reported_by:peer||user?.id||'editor',reported_at:now()},updated_at:now()};
    await wr(files.captions,a);return json(res,200,{ok:true,data:a[i]});
  }
  if(!target||!translation)return json(res,400,{ok:false,error:'translation_required'});
  a[i]={...a[i],translations:{...(a[i].translations||{}),[target]:translation},assurance:{...(a[i].assurance||{}),[target]:{provider:'manual',translation_provider:'manual',score:100,light:'green',issues:[]}},translation_feedback:{...(a[i].translation_feedback||{}),[target]:{status:'corrected',reported_by:peer||user?.id||'editor',reported_at:now()}},updated_at:now()};
  await wr(files.captions,a);return json(res,200,{ok:true,data:a[i]});
}
if(captionEditItem&&req.method==='DELETE'){
  const b=await body(req),peer=String(b.peer_id||''),user=await me(req),a=await rd(files.captions),i=a.findIndex(x=>x.id===captionEditItem[2]&&x.meeting_id===captionEditItem[1]);
  if(i<0)return json(res,404,{ok:false,error:'caption_not_found'});
  const meeting=(await rd(files.meetings)).find(x=>x.id===captionEditItem[1]),host=!!peer&&meeting?.host_peer_id===peer,own=!!peer&&a[i].peer_id===peer,admin=user?.role==='admin';
  if(!own&&!host&&!admin)return json(res,403,{ok:false,error:'caption_delete_forbidden'});
  const [deleted]=a.splice(i,1);await wr(files.captions,a);await emit('caption.deleted',{meeting_id:captionEditItem[1],caption_id:captionEditItem[2],deleted_by:peer||user?.id||'editor'});
  return json(res,200,{ok:true,data:{id:deleted.id,deleted:true}});
}
const fin=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)\/finalize$/);if(fin&&req.method==='POST')return json(res,200,{ok:true,data:await finalize(fin[1])});const localize=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)\/result\/localize$/);if(localize&&req.method==='POST'){const b=await body(req),language=String(b.language||'ko-KR'),results=await rd(files.results),i=results.findIndex(x=>x.meeting_id===localize[1]);if(i<0)return json(res,404,{ok:false,error:'meeting_result_not_found'});if(results[i].localized_results?.[language])return json(res,200,{ok:true,data:results[i]});const caps=(await rd(files.captions)).filter(x=>x.meeting_id===localize[1]),base=summarizeCaptions(caps),settings=await rd(files.settings);if(!caps.some(c=>String(c.text||'').trim())){base.summary='정리할 회의 내용 없음';base.decisions=[];base.risks=[];base.actions=[]}const tr=async text=>{if(!String(text||'').trim())return'';const out=await translate(String(text),language,settings);return out.text||String(text)};const localized={summary:await tr(base.summary),decisions:await Promise.all((base.decisions||[]).map(tr)),risks:await Promise.all((base.risks||[]).map(tr)),actions:await Promise.all((base.actions||[]).map(async x=>({...x,text:await tr(x.text||x)}))),source_count:caps.length};results[i]={...results[i],localized_results:{...(results[i].localized_results||{}),[language]:localized}};await wr(files.results,results);return json(res,200,{ok:true,data:results[i]})}const result=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)\/result$/);if(result&&req.method==='GET'){const r=(await rd(files.results)).find(x=>x.meeting_id===result[1]);return r?json(res,200,{ok:true,data:r}):json(res,404,{ok:false})}
const filePath=path.normalize(path.join(publicDir,u.pathname==='/'?'index.html':u.pathname));if(!filePath.startsWith(publicDir))return json(res,403,{ok:false});try{const data=await fs.readFile(filePath),ext=path.extname(filePath),ct=ext==='.html'?'text/html; charset=utf-8':ext==='.js'?'text/javascript; charset=utf-8':ext==='.css'?'text/css; charset=utf-8':ext==='.json'?'application/json; charset=utf-8':ext==='.webmanifest'?'application/manifest+json':'application/octet-stream';res.writeHead(200,{'content-type':ct,'cache-control':ext==='.html'||ext==='.js'?'no-cache, no-store, must-revalidate':'public, max-age=300'});return res.end(data)}catch{if(u.pathname==='/privacy')return serveText(res,'개인정보처리방침','수집 정보는 계정, 회의 참가 정보, 선택 동의 정보이며 음성 원본은 기본적으로 처리 후 삭제 정책입니다. 광고 개인화는 기본 비활성화이며 이메일·전화번호 등 PII를 광고 태그로 전송하지 않습니다.');if(u.pathname==='/terms')return serveText(res,'이용약관','VoiceFlow는 회의와 업무 생산성을 위한 서비스입니다. 녹음·화상 사용 시 참가자의 고지와 동의를 준수해야 합니다.');if(u.pathname==='/account-delete')return serveText(res,'계정 삭제 안내','앱의 내 계정 메뉴에서 계정 삭제를 요청할 수 있으며 계정은 비활성화 및 개인정보 최소화 절차를 거칩니다.');return json(res,404,{ok:false,error:'not_found'})}
}catch(e){return json(res,500,{ok:false,error:'server_error',detail:e.message})}});
server.listen(port,'0.0.0.0',()=>console.log(`VoiceFlow Meeting Core v2 :${port}`));
