import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const __dirname=path.dirname(fileURLToPath(import.meta.url)), publicDir=path.join(__dirname,'public'), dataDir=path.join(__dirname,'data');
const files=Object.fromEntries(['tasks','meetings','captions','events','users','sessions','consents'].map(k=>[k,path.join(dataDir,`${k}.json`)]));files.settings=path.join(dataDir,'settings.json');
const port=Number(process.env.PORT||4173);await fs.mkdir(dataDir,{recursive:true});
const defaultSettings={tenant_id:'demo-star45',translation:{green:90,yellow:70},providers:{stt:'browser',translation:'prototype',validator:'local'},providerCatalog:{stt:['browser','openai','google','azure'],translation:['prototype','openai','gemini','google','azure','deepl'],validator:['local','openai','gemini']},privacy:{audioRetention:'delete_after_processing',analytics:false,adsPersonalization:false},updated_at:new Date().toISOString()};
for(const [k,f] of Object.entries(files)){try{await fs.access(f)}catch{await fs.writeFile(f,k==='settings'?JSON.stringify(defaultSettings,null,2):'[]')}}
const json=(res,s,b,h={})=>{const p=JSON.stringify(b);res.writeHead(s,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*',...h});res.end(p)};
const readBody=async req=>{let r='';for await(const c of req)r+=c;return r?JSON.parse(r):{}};const readJson=async f=>JSON.parse(await fs.readFile(f,'utf8'));const writeJson=(f,d)=>fs.writeFile(f,JSON.stringify(d,null,2));const id=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;const now=()=>new Date().toISOString();
const cookie=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return[x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));
const hashPassword=(p,s=crypto.randomBytes(16).toString('hex'))=>({salt:s,hash:crypto.pbkdf2Sync(p,s,120000,32,'sha256').toString('hex')});
async function currentUser(req){const sid=cookie(req).voiceflow_session;if(!sid)return null;const sessions=await readJson(files.sessions),s=sessions.find(x=>x.id===sid&&Date.parse(x.expires_at)>Date.now());if(!s)return null;return (await readJson(files.users)).find(u=>u.id===s.user_id&&!u.deleted_at)||null}
const safeUser=u=>u&&({id:u.id,name:u.name,email:u.email,role:u.role,status:u.status,created_at:u.created_at});
async function emit(type,payload={}){const a=await readJson(files.events),e={id:id('evt'),type,payload,created_at:now()};a.unshift(e);await writeJson(files.events,a.slice(0,1000));return e}
function structureTask(text=''){const n=new Date();let deadline='';if(/오늘/.test(text))deadline=n.toISOString().slice(0,10);if(/내일/.test(text)){const d=new Date(n);d.setDate(d.getDate()+1);deadline=d.toISOString().slice(0,10)}if(/금요일/.test(text)){const d=new Date(n),diff=(5-d.getDay()+7)%7||7;d.setDate(d.getDate()+diff);deadline=d.toISOString().slice(0,10)}const o=text.match(/([가-힣A-Za-z0-9_-]{2,12})(?:에게|한테)/);return{title:text.trim().slice(0,120)||'새 업무',owner:o?.[1]||'미지정',deadline,status:'todo',priority:/긴급|최우선/.test(text)?'high':'normal'}}
const translations={'Giá này đã bao gồm phí vận chuyển.':{'ko-KR':'이 가격에는 운송비가 포함되어 있습니다.'},'Giá này chưa bao gồm VAT.':{'ko-KR':'이 가격에는 VAT가 포함되어 있지 않습니다.'},'배송은 다음 주 월요일부터 시작하겠습니다.':{'vi-VN':'Việc giao hàng sẽ bắt đầu từ thứ Hai tuần tới.'}};
function translate(text,target){return translations[text]?.[target]||text}function validate(original,translated){const nums=(s=>s.match(/\d+(?:[.,]\d+)*/g)||[]);const a=nums(original),b=nums(translated);const number=a.every(x=>b.includes(x))?100:65;const score=Math.round(number*.3+70);return{score,light:score>=90?'green':score>=70?'yellow':'red',components:{number,semantic:score},issues:number<100?['number_mismatch']:[]}}
async function updateMeeting(mid,fn){const a=await readJson(files.meetings),i=a.findIndex(x=>x.id===mid);if(i<0)return null;a[i]=fn(a[i]);a[i].updated_at=now();await writeJson(files.meetings,a);return a[i]}
function providerQuality(settings){const p=settings.providers||{};const rows=[
{id:'stt',provider:p.stt||'browser',status:'ok',score:p.stt==='browser'?72:p.stt==='openai'?94:p.stt==='google'?93:p.stt==='azure'?91:75,recommend:p.stt==='browser'?'상용 환경은 OpenAI 또는 Google STT 비교 테스트 권장':'현재 구성 유지 후 실제 KR/VN WER 측정 권장'},
{id:'translation',provider:p.translation||'prototype',status:p.translation==='prototype'?'warning':'ok',score:p.translation==='prototype'?58:p.translation==='deepl'?93:p.translation==='openai'?95:p.translation==='gemini'?94:p.translation==='google'?92:90,recommend:p.translation==='prototype'?'Prototype 제거: OpenAI/Gemini/DeepL A-B 테스트 권장':'숫자·계약용어 포함 실제 회의 샘플 100문장 품질검사 권장'},
{id:'validator',provider:p.validator||'local',status:'ok',score:p.validator==='local'?82:p.validator==='openai'?95:p.validator==='gemini'?94:80,recommend:p.validator==='local'?'중요 계약/금액 문장은 LLM 2차 검증 병행 권장':'현재 구성 유지'}];return rows}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS','access-control-allow-headers':'content-type,x-voiceflow-role,x-tenant-id'});return res.end()}
if(u.pathname==='/api/health')return json(res,200,{ok:true,service:'voiceflow-mvp',version:'1.0.0',features:['recording-first','chat','optional-video-consent','tasks','captions','translation-assurance','auth','consent','member-admin','provider-admin','quality-diagnostics','multilingual-ui']});
if(u.pathname==='/api/v1/auth/register'&&req.method==='POST'){const b=await readBody(req),email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim(),password=String(b.password||'');if(!email.includes('@')||name.length<2||password.length<8)return json(res,400,{ok:false,error:'invalid_input'});if(!b.privacyAccepted||!b.termsAccepted)return json(res,400,{ok:false,error:'consent_required'});const users=await readJson(files.users);if(users.some(x=>x.email===email&&!x.deleted_at))return json(res,409,{ok:false,error:'email_exists'});const ph=hashPassword(password),user={id:id('usr'),name,email,passwordHash:ph.hash,passwordSalt:ph.salt,role:users.length?'member':'admin',status:'active',created_at:now()};users.push(user);await writeJson(files.users,users);const cons=await readJson(files.consents);cons.push({id:id('cns'),user_id:user.id,terms:true,privacy:true,marketing:!!b.marketingAccepted,version:'2026-08-13',created_at:now()});await writeJson(files.consents,cons);const sid=id('ses'),sessions=await readJson(files.sessions);sessions.push({id:sid,user_id:user.id,created_at:now(),expires_at:new Date(Date.now()+14*864e5).toISOString()});await writeJson(files.sessions,sessions);return json(res,201,{ok:true,user:safeUser(user)},{'set-cookie':`voiceflow_session=${sid}; Path=/; HttpOnly; SameSite=Lax; Max-Age=1209600`})}
if(u.pathname==='/api/v1/auth/login'&&req.method==='POST'){const b=await readBody(req),users=await readJson(files.users),user=users.find(x=>x.email===String(b.email||'').trim().toLowerCase()&&!x.deleted_at);if(!user||user.status!=='active')return json(res,401,{ok:false,error:'invalid_login'});const h=hashPassword(String(b.password||''),user.passwordSalt).hash;if(h!==user.passwordHash)return json(res,401,{ok:false,error:'invalid_login'});const sid=id('ses'),s=await readJson(files.sessions);s.push({id:sid,user_id:user.id,created_at:now(),expires_at:new Date(Date.now()+14*864e5).toISOString()});await writeJson(files.sessions,s);return json(res,200,{ok:true,user:safeUser(user)},{'set-cookie':`voiceflow_session=${sid}; Path=/; HttpOnly; SameSite=Lax; Max-Age=1209600`})}
if(u.pathname==='/api/v1/auth/me'&&req.method==='GET'){const me=await currentUser(req);return json(res,200,{ok:true,user:safeUser(me)})}
if(u.pathname==='/api/v1/auth/logout'&&req.method==='POST'){const sid=cookie(req).voiceflow_session,s=await readJson(files.sessions);await writeJson(files.sessions,s.filter(x=>x.id!==sid));return json(res,200,{ok:true},{'set-cookie':'voiceflow_session=; Path=/; HttpOnly; Max-Age=0; SameSite=Lax'})}
if(u.pathname==='/api/v1/account/delete'&&req.method==='POST'){const me=await currentUser(req);if(!me)return json(res,401,{ok:false,error:'unauthorized'});const users=await readJson(files.users),i=users.findIndex(x=>x.id===me.id);users[i]={...users[i],status:'deleted',deleted_at:now(),email:`deleted+${users[i].id}@invalid.local`,name:'Deleted User'};await writeJson(files.users,users);const s=await readJson(files.sessions);await writeJson(files.sessions,s.filter(x=>x.user_id!==me.id));return json(res,200,{ok:true},{'set-cookie':'voiceflow_session=; Path=/; HttpOnly; Max-Age=0; SameSite=Lax'})}
if(u.pathname==='/api/v1/admin/users'&&req.method==='GET'){const me=await currentUser(req);if(!me||me.role!=='admin')return json(res,403,{ok:false,error:'forbidden'});return json(res,200,{ok:true,data:(await readJson(files.users)).map(safeUser)})}
const userPatch=u.pathname.match(/^\/api\/v1\/admin\/users\/(usr_[A-Za-z0-9_]+)$/);if(userPatch&&req.method==='PATCH'){const me=await currentUser(req);if(!me||me.role!=='admin')return json(res,403,{ok:false,error:'forbidden'});const b=await readBody(req),a=await readJson(files.users),i=a.findIndex(x=>x.id===userPatch[1]);if(i<0)return json(res,404,{ok:false});if(['active','suspended'].includes(b.status))a[i].status=b.status;if(['admin','member'].includes(b.role))a[i].role=b.role;await writeJson(files.users,a);return json(res,200,{ok:true,data:safeUser(a[i])})}
if(u.pathname==='/api/v1/admin/settings'&&req.method==='GET')return json(res,200,{ok:true,data:await readJson(files.settings)});if(u.pathname==='/api/v1/admin/settings'&&req.method==='PATCH'){const me=await currentUser(req);if(!me||me.role!=='admin')return json(res,403,{ok:false,error:'forbidden'});const b=await readBody(req),cur=await readJson(files.settings),next={...cur,...b,providers:{...cur.providers,...(b.providers||{})},privacy:{...cur.privacy,...(b.privacy||{})},updated_at:now()};await writeJson(files.settings,next);return json(res,200,{ok:true,data:next})}
if(u.pathname==='/api/v1/admin/diagnostics'&&req.method==='GET'){const s=await readJson(files.settings),providers=providerQuality(s);return json(res,200,{ok:true,data:{providers,overall:Math.round(providers.reduce((a,x)=>a+x.score,0)/providers.length),checks:{api:true,storage:true,auth:true,meeting:true,captions:true},recommendedAction:providers.find(x=>x.score<80)?.recommend||'현재 구성 유지'}})}
if(u.pathname==='/api/v1/tasks'&&req.method==='GET')return json(res,200,{ok:true,data:await readJson(files.tasks)});if(u.pathname==='/api/v1/tasks'&&req.method==='POST'){const b=await readBody(req),a=await readJson(files.tasks),t={id:id('tsk'),...structureTask(b.text||b.title||''),created_at:now()};a.unshift(t);await writeJson(files.tasks,a);return json(res,201,{ok:true,data:t})}
const tm=u.pathname.match(/^\/api\/v1\/tasks\/(tsk_[A-Za-z0-9_]+)$/);if(tm&&req.method==='PATCH'){const b=await readBody(req),a=await readJson(files.tasks),i=a.findIndex(x=>x.id===tm[1]);if(i<0)return json(res,404,{ok:false});a[i]={...a[i],...b,updated_at:now()};await writeJson(files.tasks,a);return json(res,200,{ok:true,data:a[i]})}
if(u.pathname==='/api/v1/meetings'&&req.method==='GET')return json(res,200,{ok:true,data:await readJson(files.meetings)});if(u.pathname==='/api/v1/meetings'&&req.method==='POST'){const b=await readBody(req),a=await readJson(files.meetings),m={id:id('mtg'),type:b.type==='client'?'client':'internal',title:b.title||'새 회의',status:'live',host_peer_id:b.peer_id||'',participants:b.peer_id?[{peer_id:b.peer_id,name:b.name||'Host',language:b.language||'ko-KR',joined_at:now()}]:[],signals:[],created_at:now(),updated_at:now()};a.unshift(m);await writeJson(files.meetings,a);await emit('meeting.started',{meeting_id:m.id});return json(res,201,{ok:true,data:m})}
const mm=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)$/);if(mm&&req.method==='PATCH'){const b=await readBody(req),m=await updateMeeting(mm[1],x=>({...x,...b}));return m?json(res,200,{ok:true,data:m}):json(res,404,{ok:false})}
const meetingItem=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)$/);if(meetingItem&&req.method==='GET'){const m=(await readJson(files.meetings)).find(x=>x.id===meetingItem[1]);return m?json(res,200,{ok:true,data:m}):json(res,404,{ok:false,error:'meeting_not_found'})}const join=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)\/join$/);if(join&&req.method==='POST'){const b=await readBody(req),m=await updateMeeting(join[1],x=>({...x,participants:[...x.participants.filter(p=>p.peer_id!==b.peer_id),{peer_id:b.peer_id,name:b.name||'Guest',language:b.language||'ko-KR',joined_at:now()}]}));return json(res,m?200:404,{ok:!!m,data:m})}
const sig=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)\/signals$/);if(sig&&req.method==='POST'){const b=await readBody(req),s={id:id('sig'),from:b.from,to:b.to,type:b.type,payload:b.payload||{},created_at:Date.now()},m=await updateMeeting(sig[1],x=>({...x,signals:[...(x.signals||[]).slice(-200),s]}));return json(res,m?202:404,{ok:!!m,data:s})}if(sig&&req.method==='GET'){const peer=u.searchParams.get('peer'),since=Number(u.searchParams.get('since')||0),m=(await readJson(files.meetings)).find(x=>x.id===sig[1]);return m?json(res,200,{ok:true,data:(m.signals||[]).filter(s=>(!peer||s.to===peer)&&s.created_at>since),server_time:Date.now()}):json(res,404,{ok:false})}
const cap=u.pathname.match(/^\/api\/v1\/meetings\/(mtg_[A-Za-z0-9_]+)\/captions$/);if(cap&&req.method==='POST'){const b=await readBody(req),a=await readJson(files.captions),targets=['ko-KR','vi-VN','en-US','zh-CN'],trans={},ass={};for(const t of targets){trans[t]=translate(b.text||'',t);ass[t]=validate(b.text||'',trans[t])}const c={id:id('cap'),meeting_id:cap[1],speaker:b.speaker||'Participant',language:b.language||'ko-KR',text:b.text||'',translations:trans,assurance:ass,created_at:Date.now()};a.push(c);await writeJson(files.captions,a.slice(-5000));return json(res,201,{ok:true,data:c})}if(cap&&req.method==='GET'){const target=u.searchParams.get('target')||'ko-KR',since=Number(u.searchParams.get('since')||0),a=await readJson(files.captions);return json(res,200,{ok:true,data:a.filter(c=>c.meeting_id===cap[1]&&c.created_at>since).map(c=>({...c,translation:c.translations[target]||c.text,validation:c.assurance[target]||{score:100,light:'green'}})),server_time:Date.now()})}
if(u.pathname==='/privacy')return serveText(res,'개인정보처리방침','VoiceFlow는 계정, 회의 텍스트, 선택한 음성/사진 데이터를 서비스 제공 목적으로 처리합니다. 관리자 설정에 따라 원본 음성은 처리 후 삭제할 수 있습니다. 제3자 AI Provider 사용 시 해당 처리 사실을 공개하고 동의를 받습니다. 계정 삭제는 앱 내 설정 또는 /account-delete에서 요청할 수 있습니다.');if(u.pathname==='/terms')return serveText(res,'이용약관','VoiceFlow 서비스 이용약관. 녹음·통역 기능 사용 전 참가자 동의 및 관련 법규를 준수해야 합니다.');if(u.pathname==='/account-delete')return serveText(res,'계정 삭제','앱에 로그인한 뒤 설정 > 계정 삭제에서 요청할 수 있습니다. 접근이 어려운 경우 관리자에게 계정 삭제 요청을 제출하세요.');
let fp=u.pathname==='/'?'index.html':u.pathname.replace(/^\//,'');fp=path.normalize(fp).replace(/^\.\.(\/|\\|$)/,'');try{const d=await fs.readFile(path.join(publicDir,fp)),ext=path.extname(fp),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webmanifest':'application/manifest+json'};res.writeHead(200,{'content-type':types[ext]||'application/octet-stream'});return res.end(d)}catch{}if(!u.pathname.startsWith('/api/')){const d=await fs.readFile(path.join(publicDir,'index.html'));res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(d)}return json(res,404,{ok:false,error:'not_found'})}catch(e){console.error(e);return json(res,500,{ok:false,error:'server_error',message:e.message})}});
function serveText(res,title,text){const h=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${title}</title><body style="font-family:system-ui;max-width:760px;margin:40px auto;padding:20px"><h1>${title}</h1><p style="line-height:1.8">${text}</p><p><a href="/">VoiceFlow로 돌아가기</a></p></body></html>`;res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(h)}
server.listen(port,()=>console.log(`VoiceFlow v1.0.0 http://localhost:${port}`));