import assert from 'node:assert/strict';
import fs from 'node:fs/promises';

const audio=await fs.readFile(new URL('./public/audio-monitor.js',import.meta.url),'utf8');
const css=await fs.readFile(new URL('./public/voice-core-stability-v365.css',import.meta.url),'utf8');
const index=await fs.readFile(new URL('./public/index.html',import.meta.url),'utf8');
const deploy=await fs.readFile(new URL('./deploy/complete-to-100-v262.sh',import.meta.url),'utf8');
const provider=await fs.readFile(new URL('./scripts/verify-live-translation-provider.mjs',import.meta.url),'utf8');
const adapters=await fs.readFile(new URL('./lib/provider-adapters.mjs',import.meta.url),'utf8');
const mobileSpeechPatch=await fs.readFile(new URL('./scripts/patch-immediate-original-v358.mjs',import.meta.url),'utf8');
const mobileLivePatch=await fs.readFile(new URL('./scripts/patch-mobile-live-interim-v357.mjs',import.meta.url),'utf8');
const chatScrollPatch=await fs.readFile(new URL('./scripts/patch-chat-scroll-v348.mjs',import.meta.url),'utf8');
const pwaInstall=await fs.readFile(new URL('./public/pwa-install.js',import.meta.url),'utf8');
const compose=await fs.readFile(new URL('./deploy/docker-compose.v23.yml',import.meta.url),'utf8');
const coreService=compose.split('  voiceflow-core:')[1].split('  voiceflow-board:')[0];
const aiService=compose.split('  voiceflow-ai:')[1].split('  voiceflow-connectors:')[0];

assert.match(audio,/vf-audio-monitor-slot/);
assert.match(audio,/insertBefore\(box,toolbar\.nextSibling\)/);
assert.doesNotMatch(audio,/aria-live/);
assert.doesNotMatch(audio,/role','status/);
assert.match(css,/\.vf-audio-monitor-slot/);
assert.match(index,/voice-core-stability-v365\.css\?v=3\.6\.5/);
assert.match(index,/audio-monitor\.js\?v=3\.6\.7/);
assert.match(index,/pwa-install\.js\?v=3\.6\.6/);
assert.match(pwaInstall,/controllerchange/);
assert.match(pwaInstall,/location\.reload\(\)/);
assert.match(deploy,/verify-live-translation-provider\.mjs/);
assert.match(deploy,/live translation Provider unavailable before production replacement/);
assert.match(provider,/translated&&translated!==sample/);
assert.match(provider,/hydrateSharedHubProviders/);
assert.match(adapters,/providerCredential/);
assert.match(adapters,/process\.env\[name\]/);
assert.match(adapters,/configuredModel==='gpt-5\.6-sol'\?'gpt-5':configuredModel/);
assert.match(provider,/GEMINI_API_KEY/);
assert.match(provider,/OPENAI_API_KEY/);
assert.match(coreService,/INTEGRATION_HUB_RESOLVER_URL/);
assert.match(aiService,/INTEGRATION_HUB_RESOLVER_URL/);
assert.doesNotMatch(mobileSpeechPatch,/_mobileSpeechStartWatchdog/);
assert.doesNotMatch(mobileSpeechPatch,/void checkDevices\(false\)/);
assert.doesNotMatch(mobileSpeechPatch,/speechStartedAt=Date\.now\(\)/);
assert.match(mobileSpeechPatch,/const speechStart="try\{r\.start\(\)\}catch\(e\)\{"/);
assert.doesNotMatch(mobileSpeechPatch,/r\.start\(speechTrack\)/);
assert.match(mobileSpeechPatch,/mobileEmptyCycle=mobileSpeech&&!recognitionCycle\.result/);
assert.match(mobileSpeechPatch,/startServerSpeechFallback\(\);state\.media\.stt='server';return/);
assert.match(mobileSpeechPatch,/recognitionCycle\.error\|\|'ended-without-result'/);
assert.match(mobileSpeechPatch,/watchedGeneration=generation/);
assert.match(mobileSpeechPatch,/browser-no-result-timeout'\},1500\)/);
assert.match(mobileSpeechPatch,/source=source\.replace\(goldenCaptionCommit,optimisticCaptionCommit\)/);
assert.match(chatScrollPatch,/const moveOnce=Boolean\(forceBottom&&nearBottom&&!editorOpen/);
assert.doesNotMatch(chatScrollPatch,/current\.innerHTML=state\.captions\.slice/);
assert.match(mobileLivePatch,/state\._mobileSpeechFallbackTimer=null/);
assert.match(mobileLivePatch,/mobileSpeech&&!mobileBrowserSpeech&&code!=='no-speech'/);
assert.match(mobileLivePatch,/replaceOnce\(competingWatchdog,browserSingleOwner/);
assert.match(mobileLivePatch,/v357_competing_mobile_stt_owner_remaining/);
assert.match(mobileLivePatch,/r\.continuous=true;r\.interimResults=true/);
assert.match(mobileLivePatch,/state\.media\.stt==='error'\?1200:350/);
assert.doesNotMatch(mobileLivePatch,/'r\.continuous=!mobileSpeech;r\.interimResults=true;',/);
assert.doesNotMatch(mobileLivePatch,/setTimeout\(startSpeech,state\.media\.stt==='error'\?1200:\(mobileSpeech\?80:350\)\)/);
console.log('VoiceFlow core voice and translation stability contract passed');
