import fs from 'node:fs/promises';
import { chromium } from 'playwright';

const base=process.env.E2E_BASE_URL||'http://127.0.0.1:4173';
const expectedVersion=process.env.E2E_EXPECT_VERSION||'2.6.2';
const coreBase=process.env.E2E_CORE_URL||new URL(base).origin.replace(/:\d+$/,':4180');
const email=`e2e_${Date.now()}_${crypto.randomUUID().slice(0,8)}@star45.test`,password='E2eTest!2345';
const results=[],pageErrors=[];let registered=false,fatal=null,tapId='';
const pass=n=>{results.push({name:n,status:'PASS'});console.log(`PASS  ${n}`)};
const timeout=(n,ms=20000)=>new Promise((_,r)=>setTimeout(()=>r(new Error(`step_timeout_${ms}ms: ${n}`)),ms));
const check=async(n,fn)=>{console.log(`RUN   ${n}`);try{await Promise.race([fn(),timeout(n)]);pass(n)}catch(e){results.push({name:n,status:'FAIL',error:String(e?.stack||e)});console.error(`FAIL  ${n}:`,e);throw e}};
const browser=await chromium.launch({headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--no-sandbox','--disable-cache']});
const context=await browser.newContext({permissions:['microphone','camera'],serviceWorkers:'block',viewport:{width:390,height:844}});
const page=await context.newPage();page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(15000);
page.on('pageerror',e=>{const m=String(e?.stack||e);pageErrors.push(m);console.error('PAGEERROR',m)});
page.on('console',m=>{if(m.type()==='error'&&!/401/.test(m.text()))console.error('BROWSER',m.text())});
page.on('dialog',d=>d.dismiss().catch(()=>{}));
async function goHome(){const b=page.locator('[data-nav="home"]').first();if(await b.count())await b.click();await page.waitForTimeout(250)}
async function waitSync(){await page.waitForFunction(()=>{const e=document.querySelector('#meetingSyncState');return e&&!String(e.textContent||'').includes('서버 연결 중')},{timeout:9000});const t=await page.locator('#meetingSyncState').textContent();if(String(t).includes('확인 필요'))throw new Error(t)}
async function stopAndReview(){await page.locator('#stopCapture').click();await page.locator('#vfResultModal').waitFor({state:'visible',timeout:5000});if(!await page.locator('#resultSummaryEdit').count())throw new Error('editable result summary missing');if(!await page.locator('#saveResultLibrary').count())throw new Error('result library save action missing');if(!await page.locator('#closeResultModal2').count())throw new Error('result cancel action missing');await page.locator('#closeResultModal2').click();await page.locator('#vfResultModal').waitFor({state:'detached',timeout:5000})}
try{
 await check(`version endpoint ${expectedVersion}`,async()=>{const r=await page.request.get(`${base}/version.json?e2e=${Date.now()}`);const d=await r.json();if(d.version!==expectedVersion)throw new Error(`version=${d.version}`)});
 await check('gateway and TapJoin health',async()=>{const r=await page.request.get(`${base}/api/health`);const d=await r.json();if(!d.ok)throw new Error('gateway not healthy');if(!d.services?.deviceNearby?.ok)throw new Error('deviceNearby not healthy')});
 await check('TapJoin public pages',async()=>{for(const p of ['/tap.html','/tap-settings.html','/device-nearby-bridge.js']){const r=await page.request.get(`${base}${p}`);if(!r.ok())throw new Error(`${p} HTTP ${r.status()}`)}});
 await check('home opens',async()=>{await page.goto(`${base}/?e2e=${Date.now()}`,{waitUntil:'networkidle'})});
 await check('VoiceFlow v3 mobile artifact',async()=>{const linked=await page.evaluate(()=>[...document.styleSheets].some(x=>String(x.href||'').includes('voiceflow-ui-v300.css')));if(!linked)throw new Error('v3 mobile stylesheet missing')});
 await check('language select',async()=>{const b=page.locator('[data-lang="ko"]');if(await b.count())await b.click();await page.waitForTimeout(250)});
 await check('register/login',async()=>{await page.locator('[data-nav="account"]').first().click();const f=page.locator('#joinForm');if(await f.count()){await page.fill('#joinName','E2E Tester');await page.fill('#joinEmail',email);await page.fill('#joinPw',password);await page.check('#agreeTerms');await page.check('#agreePrivacy');if(!await f.evaluate(form=>form.checkValidity()))throw new Error('register form is invalid');const registerWait=page.waitForResponse(r=>r.url().includes('/api/v1/auth/register')&&r.request().method()==='POST',{timeout:10000});await f.evaluate(form=>form.requestSubmit());const register=await registerWait;if(!register.ok())throw new Error(`register HTTP ${register.status()} ${await register.text()}`);registered=true;await page.waitForFunction(()=>!document.querySelector('#joinForm'),{timeout:5000});const login=await page.request.post(`${base}/api/v1/auth/login`,{data:{email,password}});if(!login.ok())throw new Error(`login HTTP ${login.status()} ${await login.text()}`);const rawCookie=login.headers()['set-cookie']||'';const sid=/voiceflow_session=([^;]+)/.exec(rawCookie)?.[1];if(!sid)throw new Error('login session cookie missing');await context.addCookies([{name:'voiceflow_session',value:sid,url:base}]);const me=await page.request.get(`${base}/api/v1/auth/me`);if(!me.ok()||!(await me.json()).user)throw new Error('authenticated session check failed');await page.goto(`${base}/?e2e_login=${Date.now()}`,{waitUntil:'networkidle'})}await goHome()});
 await check('mobile bottom nav is one row',async()=>{const nav=page.locator('.bottom-nav');if(!await nav.count())throw new Error('bottom nav missing');const box=await nav.boundingBox();if(!box||box.height>80)throw new Error(`bottom nav height=${box?.height}`);const buttons=nav.locator('button');if(await buttons.count()<5)throw new Error('bottom nav items missing');const ys=await buttons.evaluateAll(bs=>bs.map(b=>Math.round(b.getBoundingClientRect().top)));if(new Set(ys).size!==1)throw new Error(`nav not one row: ${ys.join(',')}`)});
 await check('Android root keeps PC-style home and starts server-capable room',async()=>{const mobileContext=await browser.newContext({permissions:['microphone','camera'],serviceWorkers:'block',viewport:{width:390,height:844},userAgent:'Mozilla/5.0 (Linux; Android 14; SM-S928N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Mobile Safari/537.36'});await mobileContext.addCookies(await context.cookies());await mobileContext.addInitScript(()=>{try{localStorage.uiLanguage='ko'}catch{}});const mobilePage=await mobileContext.newPage();try{await mobilePage.goto(`${base}/?e2e_android_classic=${Date.now()}`,{waitUntil:'networkidle'});if(new URL(mobilePage.url()).pathname!=='/')throw new Error('Android left PC-style root: '+mobilePage.url());if(await mobilePage.locator('html').getAttribute('data-v4-controls'))throw new Error('Android v4 four-control route still active');if(!await mobilePage.locator('#quickAudioStart').isVisible())throw new Error('Android PC-style voice start missing');for(const id of ['startMicrophone','stopMicrophone','startSpeech','finishSpeech']){if(await mobilePage.locator('#'+id).count())throw new Error('Android obsolete '+id+' visible')}const createWait=mobilePage.waitForResponse(r=>/\/api\/v1\/meetings$/.test(new URL(r.url()).pathname)&&r.request().method()==='POST',{timeout:10000});await mobilePage.locator('#quickAudioStart').click();const created=await createWait;if(!created.ok())throw new Error(`meeting create HTTP ${created.status()} ${await created.text()}`);await mobilePage.locator('#stopCapture').waitFor({state:'visible',timeout:5000});if(!await mobilePage.locator('#speechState').count())throw new Error('Android server-capable speech state missing')}finally{await mobileContext.close()}});
 await check('installed PWA keeps PC-style home and starts server-capable room',async()=>{const pwaContext=await browser.newContext({permissions:['microphone','camera'],serviceWorkers:'block',viewport:{width:390,height:844},userAgent:'Mozilla/5.0 (Linux; Android 14; SM-S928N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Mobile Safari/537.36'});await pwaContext.addCookies(await context.cookies());await pwaContext.addInitScript(()=>{const nativeMatchMedia=window.matchMedia.bind(window);Object.defineProperty(window,'matchMedia',{configurable:true,value:query=>query==='(display-mode: standalone)'?{matches:true,media:query,onchange:null,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){},dispatchEvent(){return true}}:nativeMatchMedia(query)});try{localStorage.uiLanguage='ko'}catch{}});const pwaPage=await pwaContext.newPage();try{await pwaPage.goto(`${base}/?e2e_pwa_classic=${Date.now()}`,{waitUntil:'networkidle'});if(new URL(pwaPage.url()).pathname!=='/')throw new Error('installed PWA left PC-style root: '+pwaPage.url());if(await pwaPage.locator('html').getAttribute('data-v4-controls'))throw new Error('installed PWA v4 four-control route still active');if(!await pwaPage.locator('#quickAudioStart').isVisible())throw new Error('installed PWA PC-style voice start missing');for(const id of ['startMicrophone','stopMicrophone','startSpeech','finishSpeech']){if(await pwaPage.locator('#'+id).count())throw new Error('installed PWA obsolete '+id+' visible')}const createWait=pwaPage.waitForResponse(r=>/\/api\/v1\/meetings$/.test(new URL(r.url()).pathname)&&r.request().method()==='POST',{timeout:10000});await pwaPage.locator('#quickAudioStart').click();const created=await createWait;if(!created.ok())throw new Error(`meeting create HTTP ${created.status()} ${await created.text()}`);await pwaPage.locator('#stopCapture').waitFor({state:'visible',timeout:5000});if(!await pwaPage.locator('#speechState').count())throw new Error('installed PWA server-capable speech state missing')}finally{await pwaContext.close()}});
 await check('home voice start opens recording room',async()=>{const createWait=page.waitForResponse(r=>/\/api\/v1\/meetings$/.test(new URL(r.url()).pathname)&&r.request().method()==='POST',{timeout:10000});await page.locator('#quickAudioStart').click();const created=await createWait;if(!created.ok())throw new Error(`meeting create HTTP ${created.status()} ${await created.text()}`);await page.locator('#stopCapture').waitFor({state:'visible',timeout:5000});await goHome()});
 await check('digital card profile and NFC fixed URL',async()=>{let r=await page.request.patch(`${base}/api/v1/tapjoin/profile`,{data:{name:'E2E Tester',company:'STAR45',title:'Tester',phone:'+8200000000',email}});if(!r.ok())throw new Error(`profile save HTTP ${r.status()} ${await r.text()}`);const d=await r.json();tapId=d.data?.tap_id;if(!tapId||!d.nfc_url?.includes('/tap.html?id='))throw new Error('fixed NFC URL missing');r=await page.request.get(`${base}/api/v1/tapjoin/card/${encodeURIComponent(tapId)}?format=vcard`);if(!r.ok())throw new Error('vCard download failed');const vc=await r.text();if(!vc.includes('BEGIN:VCARD')||!vc.includes('STAR45'))throw new Error('vCard invalid')});
 await check('current voice recording flow',async()=>{await goHome();const ongoing=page.locator('[data-nav="room"]');if(await ongoing.count())await ongoing.first().click();else await page.locator('#quickAudioStart').click();await page.locator('#stopCapture').waitFor({state:'visible',timeout:4000});if(!await page.locator('#vfAudioMonitor').count()||!await page.locator('#vfQualityLabel').count())throw new Error('stable live quality monitor missing');if(!await page.locator('.vf-toolbar-recording').count())throw new Error('recording status missing');if(!await page.locator('#pauseCapture').count())throw new Error('pause control missing');await page.locator('#pauseCapture').click();await page.waitForTimeout(200);if(!await page.locator('#pauseCapture').count())throw new Error('resume control missing');await page.locator('#pauseCapture').click()});
 await check('mobile voice room has no duplicate title or horizontal overflow',async()=>{const metrics=await page.evaluate(()=>{const title='음성메모 · 기본 대화방';const count=document.body.innerText.split(title).length-1;const shell=document.querySelector('.shell')?.getBoundingClientRect();return{count,shellWidth:shell?.width||0,viewport:document.documentElement.clientWidth,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth}});if(metrics.count!==1)throw new Error('duplicated room title count='+metrics.count);if(metrics.overflow>2)throw new Error('horizontal overflow='+metrics.overflow);if(metrics.shellWidth<metrics.viewport-2)throw new Error('mobile shell is not full width')});
 await check('unsupported browser STT is not shown as listening',async()=>{const unsupported=await page.evaluate(()=>!(window.SpeechRecognition||window.webkitSpeechRecognition));if(unsupported){const text=await page.locator('#speechState').textContent();if(!String(text).includes('지원하지 않습니다'))throw new Error('unsupported STT falsely shown as listening: '+text)}});
 await check('current chat and invite flow',async()=>{const composer=page.locator('#chatText');if(await composer.evaluate(el=>el.tagName)!=='TEXTAREA')throw new Error('chat composer is not multiline');await page.selectOption('#liveTargetLang','en-US');await composer.fill('E2E 채팅 첫 줄\nE2E 채팅 둘째 줄');await page.locator('#sendChat').click();await page.waitForFunction(()=>document.body.innerText.includes('E2E 채팅 첫 줄')&&document.body.innerText.includes('E2E 채팅 둘째 줄'),{timeout:5000});const body=await page.textContent('body');if(!body.includes('E2E 채팅 첫 줄')||!body.includes('E2E 채팅 둘째 줄'))throw new Error('multiline chat text missing');if(!await page.locator('#inviteInline').count())throw new Error('inline invite missing')});
 await check('recording stop and result review',async()=>{await stopAndReview()});
 await check('AI task natural-language intake',async()=>{await goHome();await page.locator('[data-nav="work"]').first().click();await page.fill('#taskText','김대리에게 내일 오후 3시 재고회의 등록하고 알려줘');await page.locator('#taskInterpret').click();await page.locator('#taskBatchSave').waitFor({state:'visible',timeout:5000});if(!await page.locator('[data-draft]').count())throw new Error('task draft missing')});
 await check('admin integration guide and Device connector UI',async()=>{const guarded=await page.request.get(`${base}/admin-integrations.html?guard=${Date.now()}`,{maxRedirects:0,headers:{'cache-control':'no-cache','pragma':'no-cache'}});if(guarded.status()!==302||!String(guarded.headers().location||'').includes('admin_required=1'))throw new Error(`regular user admin guard failed: HTTP ${guarded.status()} location=${guarded.headers().location||''}`);const r=await page.request.get(`${coreBase}/admin-integrations.html?e2e=${Date.now()}`,{headers:{'cache-control':'no-cache','pragma':'no-cache'}});const t=await r.text();const missing=[['autoConfigure','id="autoConfigure"'],['openHub','id="openHub"'],['admin-mobile-nav','admin-mobile-nav'],['voiceflow-admin-v3','voiceflow-admin-v3']].filter(([,marker])=>!t.includes(marker)).map(([name])=>name);if(missing.length)throw new Error(`integration/Hub v3 page missing: ${missing.join(', ')} HTTP ${r.status()}`);const j=await page.request.get(`${base}/admin-integrations.js?e2e=${Date.now()}`);const js=await j.text();if(!js.includes('연결 방법')||!js.includes('device_tapjoin')||!js.includes('Hub→앱')||!js.includes('앱→Hub'))throw new Error('admin Device/Hub guide missing')});
 await check('no browser page errors',async()=>{if(pageErrors.length)throw new Error(pageErrors.join('\n---\n'))});
}catch(e){fatal=e}
finally{if(registered){try{await page.request.post(`${base}/api/v1/account/delete`)}catch{}}await browser.close();const passed=results.filter(x=>x.status==='PASS').length;console.log(`E2E RESULT ${passed}/${results.length} PASS`);if(process.env.E2E_REPORT_FILE)await fs.writeFile(process.env.E2E_REPORT_FILE,JSON.stringify({passed,total:results.length,ok:!fatal,results,pageErrors},null,2));if(fatal)process.exitCode=1}
