import fs from 'node:fs/promises';
import path from 'node:path';

const dataDir=process.env.AUTOMATION_DATA_DIR||'./data';
const vaultPath=process.env.OBSIDIAN_VAULT_PATH||'';
const bridgeDir=process.env.HERMES_BRIDGE_DIR||'';
const pollMs=Math.max(30000,Number(process.env.AUTOMATION_POLL_MS||60000));
const resultsFile=path.join(dataDir,'results.json');
const meetingsFile=path.join(dataDir,'meetings.json');
const tasksFile=path.join(dataDir,'tasks.json');
const reviewsFile=path.join(dataDir,'meeting-result-reviews.json');
const driveIndexFile=path.join(dataDir,'meeting-drive-index.json');
const stateFile=path.join(dataDir,'automation-worker-state.json');
const auditFile=path.join(dataDir,'automation-worker-audit.json');
await fs.mkdir(dataDir,{recursive:true});
for(const f of [resultsFile,meetingsFile,tasksFile,reviewsFile,driveIndexFile,auditFile]){try{await fs.access(f)}catch{await fs.writeFile(f,'[]')}}
try{await fs.access(stateFile)}catch{await fs.writeFile(stateFile,JSON.stringify({processed_results:[],processed_task_sync:[]},null,2))}
const rd=async(f,fallback=[])=>{try{return JSON.parse(await fs.readFile(f,'utf8'))}catch{return fallback}};
const wr=(f,d)=>fs.writeFile(f,JSON.stringify(d,null,2));
const now=()=>new Date().toISOString();
const uid=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const clean=s=>String(s||'Untitled').replace(/[\\/:*?"<>|]/g,'-').replace(/\.\./g,'').trim().slice(0,120)||'Untitled';
async function audit(type,payload={}){const a=await rd(auditFile);a.unshift({id:uid('aut'),type,payload,created_at:now()});await wr(auditFile,a.slice(0,3000))}
async function discordApi(endpoint,opt={}){const token=process.env.DISCORD_BOT_TOKEN;if(!token)throw new Error('discord_not_configured');const r=await fetch(`https://discord.com/api/v10${endpoint}`,{...opt,headers:{authorization:`Bot ${token}`,'content-type':'application/json',...(opt.headers||{})},signal:AbortSignal.timeout(12000)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||`discord_http_${r.status}`);return d}
async function writeMeetingNote(result,meeting,driveRef){if(!vaultPath)return null;const dir=path.join(vaultPath,'Meetings');await fs.mkdir(dir,{recursive:true});const title=clean(`${new Date(result.created_at||Date.now()).toISOString().slice(0,10)} ${meeting?.title||result.meeting_id}`);const file=path.join(dir,`${title}.md`);const decisions=(result.decisions||[]).map(x=>`- ${typeof x==='string'?x:JSON.stringify(x)}`).join('\n')||'- 없음';const actions=(result.actions||[]).map(x=>`- ${x.text||x} ${x.owner?`(@${x.owner})`:''} ${x.deadline?`(${x.deadline})`:''}`).join('\n')||'- 없음';const risks=(result.risks||[]).map(x=>`- ${typeof x==='string'?x:JSON.stringify(x)}`).join('\n')||'- 없음';const text=`---\nsource: Google Drive\nmeeting_id: ${JSON.stringify(result.meeting_id)}\ndrive_url: ${JSON.stringify(driveRef?.drive_url||'')}\napproved_at: ${JSON.stringify(driveRef?.approved_at||'')}\nprovider: ${JSON.stringify(result.provider||'local')}\n---\n\n# ${title}\n\n> 공식 원본: ${driveRef?.drive_url||'Google Drive'}\n\n## 요약\n${result.summary||'요약 없음'}\n\n## 결정사항\n${decisions}\n\n## Action Items\n${actions}\n\n## Risks\n${risks}\n`;await fs.writeFile(file,text,'utf8');return path.relative(vaultPath,file)}
async function queueHermes(result,meeting,noteFile,driveRef){if(!bridgeDir)return null;await fs.mkdir(bridgeDir,{recursive:true});const row={job_id:uid('hrm'),type:'meeting-approved-postprocess',instruction:'Google Drive에 승인 저장된 공식 회의결과를 기준으로 SOP 업데이트 후보, 재사용 가능한 회사 지식, 후속 업무 누락 여부를 제안하세요. 새로운 사실을 만들지 말고 승인 후보만 작성하세요.',context:{meeting_id:result.meeting_id,title:meeting?.title||'',google_drive_url:driveRef?.drive_url||'',obsidian_note:noteFile||'',summary:result.summary||'',decisions:result.decisions||[],actions:result.actions||[],risks:result.risks||[]},status:'pending',created_at:now()};await fs.writeFile(path.join(bridgeDir,`${row.job_id}.json`),JSON.stringify(row,null,2));return row.job_id}
async function postMeetingDiscord(result,meeting,driveRef){const channel=process.env.DISCORD_NOTICE_CHANNEL_ID;if(!channel||!process.env.DISCORD_BOT_TOKEN)return null;const summary=String(result.summary||'회의가 승인 완료되었습니다.').slice(0,1100);const link=driveRef?.drive_url?`\n공식 회의결과: ${driveRef.drive_url}`:'';const content=`**회의결과 승인 · ${meeting?.title||result.meeting_id}**\n${summary}\n\nAction Items: ${(result.actions||[]).length}개 · 결정사항: ${(result.decisions||[]).length}개${link}`;const d=await discordApi(`/channels/${channel}/messages`,{method:'POST',body:JSON.stringify({content})});return d.id}
async function syncTaskDiscord(task){if(!process.env.DISCORD_BOT_TOKEN||!process.env.DISCORD_GUILD_ID||!process.env.DISCORD_VOICE_CHANNEL_ID)return null;if(!task.deadline)return null;const start=new Date(task.start_at||task.deadline);if(Number.isNaN(start.getTime()))return null;if(!task.start_at&&task.time){const [h,m]=String(task.time).split(':').map(Number);if(Number.isFinite(h))start.setHours(h,Number.isFinite(m)?m:0,0,0)}const end=new Date(start.getTime()+Math.max(30,Number(task.duration_minutes||60))*60000);const payload={name:String(task.title||'VoiceFlow Task').slice(0,100),description:String(task.description||`담당: ${task.owner||'미지정'}`).slice(0,1000),privacy_level:2,entity_type:2,channel_id:process.env.DISCORD_VOICE_CHANNEL_ID,scheduled_start_time:start.toISOString(),scheduled_end_time:end.toISOString()};return discordApi(`/guilds/${process.env.DISCORD_GUILD_ID}/scheduled-events`,{method:'POST',body:JSON.stringify(payload)})}
async function run(){const state=await rd(stateFile,{processed_results:[],processed_task_sync:[]});state.processed_results=state.processed_results||[];state.processed_task_sync=state.processed_task_sync||[];const results=await rd(resultsFile),meetings=await rd(meetingsFile),reviews=await rd(reviewsFile),driveIndex=await rd(driveIndexFile);for(const result of results){const key=result.id||result.meeting_id;if(!key||state.processed_results.includes(key))continue;const review=reviews.find(x=>x.meeting_id===result.meeting_id&&x.status==='approved'),driveRef=driveIndex.find(x=>x.meeting_id===result.meeting_id);if(!review||!driveRef)continue;const meeting=meetings.find(x=>x.id===result.meeting_id);try{const note=await writeMeetingNote(result,meeting,driveRef);const hermes=await queueHermes(result,meeting,note,driveRef);let discord=null;try{discord=await postMeetingDiscord(result,meeting,driveRef)}catch(e){await audit('meeting.discord.failed',{meeting_id:result.meeting_id,error:e.message})}state.processed_results.push(key);state.processed_results=state.processed_results.slice(-2000);await audit('meeting.approved.postprocessed',{meeting_id:result.meeting_id,drive_url:driveRef.drive_url,note,hermes_job_id:hermes,discord_message_id:discord})}catch(e){await audit('meeting.postprocess.failed',{meeting_id:result.meeting_id,error:e.message})}}
const tasks=await rd(tasksFile);let changed=false;for(const task of tasks){if(!task.discord_sync_requested||task.discord_event_id||state.processed_task_sync.includes(task.id))continue;try{const event=await syncTaskDiscord(task);if(!event)continue;task.discord_event_id=event.id;task.calendar_sync={...(task.calendar_sync||{}),discord:'synced'};task.updated_at=now();state.processed_task_sync.push(task.id);state.processed_task_sync=state.processed_task_sync.slice(-3000);changed=true;await audit('task.discord.synced',{task_id:task.id,event_id:event.id})}catch(e){task.calendar_sync={...(task.calendar_sync||{}),discord:'error'};task.discord_sync_error=e.message;changed=true;await audit('task.discord.failed',{task_id:task.id,error:e.message})}}if(changed)await wr(tasksFile,tasks);await wr(stateFile,state)}
let running=false;
async function runOnce(){
  if(running){console.warn('automation-worker: skipped overlapping cycle');return}
  running=true;
  try{await run()}finally{running=false}
}
console.log(`VoiceFlow Automation Worker poll=${pollMs}ms approval-gated overlap-guarded`);
await runOnce();
setInterval(()=>runOnce().catch(e=>console.error('automation-worker',e)),pollMs).unref?.();
