import fs from 'node:fs/promises';

const file=new URL('../public/app.js',import.meta.url);
let s=await fs.readFile(file,'utf8');
const must=(re,repl,label)=>{if(!re.test(s))throw new Error(`patch_missing:${label}`);s=s.replace(re,repl)};

must(/media:\{stream:null,mic:'idle',recording:false,startedAt:0,timer:null,elapsed:0\},video:\{incoming:null,status:'off',imageUrl:null\}/,
"media:{stream:null,mic:'idle',camera:'idle',recording:false,startedAt:0,timer:null,elapsed:0,testUrl:null},video:{incoming:null,status:'off',imageUrl:null,enabledByOption:false}",'media-state');

must(/function meetingStart\(type\)\{.*?\}\nconst fmt=/s,
`function meetingStart(type){const client=type==='client';return shell(\`<section class="page-head"><div><small>\${client?'CLIENT SESSION':'INTERNAL SESSION'}</small><h1>\${client?t('client'):t('meeting')}</h1></div></section><section class="voice-first-banner"><div><span>●</span><b>회의 준비</b></div><p>회의방 입장 시 카메라·마이크 상태만 점검합니다. 녹음은 자동으로 시작하지 않습니다.</p></section><section class="composer elevated"><label>제목<input id="meetingTitle" value="\${client?'Partner Meeting':'Operations Meeting'}"></label><div class="form-grid"><label>이름<input id="meetingName" value="\${esc(state.user?.name||localStorage.displayName||'Host')}"></label><label>내 언어<select id="meetingLang"><option value="ko-KR">한국어</option><option value="vi-VN">Tiếng Việt</option><option value="en-US">English</option><option value="zh-CN">中文</option></select></label></div><div class="panel"><b>회의 방식</b><label class="check"><input type="radio" name="meetingMode" value="voice" checked><span>음성 중심 회의</span></label><label class="check"><input type="radio" name="meetingMode" value="video"><span>화상회의 가능</span></label></div><div class="quick-actions"><button type="button" id="deviceTest">카메라·마이크·시험녹음</button></div><div id="deviceTestResult" class="small">사전 테스트 미실시</div><button id="meetingStart" class="primary">회의방 입장</button><small class="privacy-note">입장 ≠ 녹음 시작 · 화상 송출은 상대방 동의 후 실행됩니다.</small></section>\`)}
const fmt=`,'meeting-start-ui');

must(/function room\(\)\{.*?\}\nfunction joinPage/s,
`function room(){const m=state.meeting;if(!m)return home();const cam=state.media.camera==='ok'?'카메라 정상':state.media.camera==='error'?'카메라 확인 필요':'카메라 확인 중';const mic=state.media.mic==='ok'?'마이크 정상':state.media.mic==='error'?'마이크 확인 필요':'마이크 확인 중';const sync=m._creating?' · 서버 연결 중':m._createError?' · 서버 연결 실패':'';return shell(\`<section class="room-head"><div><small>\${m.type==='client'?'CLIENT MEETING':'INTERNAL MEETING'}</small><h1>\${esc(m.title)}</h1><small id="meetingSyncState">\${sync}</small></div><div class="live-badge"><span></span>LIVE</div></section>\${state.video.incoming?\`<section class="video-consent"><b>화상 연결 요청</b><p>거절해도 채팅·통번역은 계속됩니다.</p><div><button id="rejectVideo">거절</button><button id="acceptVideo" class="primary-mini">수락</button></div></section>\`:''}<section class="record-panel premium-rec"><div class="record-orb \${state.media.recording?'active':''}"><span></span></div><div><small>MEETING SESSION</small><h2>\${state.media.recording?'녹음 중':'녹음 대기'}</h2><b id="recordTime">\${fmt(state.media.elapsed)}</b></div><span class="mic-state \${state.media.mic}">\${mic} · \${cam}</span></section><section class="quick-actions"><button id="recordToggle" class="\${state.media.recording?'danger':''}">\${state.media.recording?'녹음 중지':'● 녹음 시작'}</button><button id="micCheck">장치 재확인</button><button id="invite">초대 링크</button><button id="videoRequest">화상 요청</button><button id="imageMode">이미지 송출</button><input id="visualFile" type="file" accept="image/*" hidden></section>\${state.video.imageUrl?\`<section class="visual-panel"><img src="\${state.video.imageUrl}" alt="shared"></section>\`:''}<section class="chat-composer"><input id="chatText" placeholder="메모 또는 채팅을 입력하세요"><button id="sendChat">전송</button></section><section class="panel transcript-panel"><div class="panel-title"><div><small>LIVE BILINGUAL STREAM</small><h2>원문 · 상대방 번역 · 검정</h2></div><span>\${state.captions.length}</span></div>\${state.captions.slice(-12).map(captionCard).join('')||'<div class="empty premium-empty"><b>녹음 대기 중</b><span>녹음 시작 후 음성이 원문·번역·검정으로 표시됩니다.</span></div>'}</section><section class="controls"><button data-nav="home">홈으로</button><button id="endMeeting" class="danger">회의 종료</button></section>\`)}
function joinPage`,'room-ui');

must(/async function startMeeting\(type\)\{.*?\}\nasync function postCaption/s,
`const withTimeout=(p,ms,label)=>Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(new Error(label||'timeout')),ms))]);
function enterMeetingRoom(type){const name=$('#meetingName')?.value||'Host',language=$('#meetingLang')?.value||locale[state.lang],title=$('#meetingTitle')?.value||'Meeting',mode=document.querySelector('input[name="meetingMode"]:checked')?.value||'voice';localStorage.displayName=name;localStorage.language=language;state.video.enabledByOption=mode==='video';state.meeting={id:null,type,title,status:'creating',participants:[],_peer:null,meeting_mode:mode,_creating:true};state.view='room';state.captions=[];state.media.elapsed=0;state.media.recording=false;render();setTimeout(()=>{void syncMeetingCreate({type,title,name,language,mode})},0);setTimeout(()=>{void checkDevices(mode==='video').catch(()=>{})},0)}
async function syncMeetingCreate({type,title,name,language,mode}){const peer=\`peer_\${crypto.randomUUID().slice(0,8)}\`;if(state.meeting)state.meeting._peer=peer;try{const created=await withTimeout(api('/api/v1/meetings',{method:'POST',body:JSON.stringify({type,title,peer_id:peer,name,language,meeting_mode:mode})}),8000,'meeting_create_timeout');if(!state.meeting)return;state.meeting={...(created.data||{}),_peer:peer,meeting_mode:mode,_creating:false};render();pollCaptions();pollSignals()}catch(e){if(state.meeting){state.meeting={...state.meeting,_creating:false,_createError:e.message};render()}}}
function quickJoin(){const name=$('#joinGuestName')?.value||'Guest',language=$('#joinGuestLang')?.value||locale[state.lang];state.meeting={id:null,type:'internal',title:'Joining meeting',status:'creating',participants:[],_peer:null,_creating:true};state.view='room';state.media.recording=false;render();setTimeout(()=>{void syncQuickJoin({name,language})},0);setTimeout(()=>{void checkDevices(false).catch(()=>{})},0)}
async function syncQuickJoin({name,language}){const peer=\`peer_\${crypto.randomUUID().slice(0,8)}\`;if(state.meeting)state.meeting._peer=peer;try{const r=await withTimeout(api(\`/api/v1/meetings/\${state.joinId}/join\`,{method:'POST',body:JSON.stringify({peer_id:peer,name,language})}),8000,'meeting_join_timeout');if(!state.meeting)return;state.meeting={...r.data,_peer:peer,_creating:false};localStorage.language=language;localStorage.displayName=name;render();pollCaptions();pollSignals()}catch(e){if(state.meeting){state.meeting={...state.meeting,_creating:false,_createError:e.message};render()}}}
async function checkDevices(keepVideo=false){state.media.mic='checking';state.media.camera='checking';render();try{state.media.stream?.getTracks().forEach(x=>x.stop());const audio=await withTimeout(navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false}),7000,'microphone_timeout');state.media.stream=audio;state.media.mic=audio.getAudioTracks()[0]?.readyState==='live'?'ok':'error'}catch{state.media.mic='error'}try{const cam=await withTimeout(navigator.mediaDevices.getUserMedia({video:true,audio:false}),7000,'camera_timeout');state.media.camera=cam.getVideoTracks()[0]?.readyState==='live'?'ok':'error';if(keepVideo){state.video._cameraStream=cam;state.video.status='카메라 준비'}else cam.getTracks().forEach(x=>x.stop())}catch{state.media.camera='error';state.video.status='카메라 연결 실패'}render()}
async function runDeviceTest(){const out=$('#deviceTestResult');if(out)out.textContent='장치 테스트 중...';let mic='실패',cam='실패',rec='미지원',audio=null;try{audio=await withTimeout(navigator.mediaDevices.getUserMedia({audio:true,video:false}),7000,'microphone_test_timeout');mic='정상'}catch{}try{const v=await withTimeout(navigator.mediaDevices.getUserMedia({video:true,audio:false}),7000,'camera_test_timeout');cam='정상';v.getTracks().forEach(x=>x.stop())}catch{}try{if(audio&&window.MediaRecorder){const chunks=[];const mr=new MediaRecorder(audio);mr.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};mr.start();await new Promise(r=>setTimeout(r,2500));await new Promise(r=>{mr.onstop=r;mr.stop()});const blob=new Blob(chunks,{type:chunks[0]?.type||'audio/webm'});rec=blob.size>0?\`정상 (\${Math.round(blob.size/1024)}KB)\`:'실패';if(state.media.testUrl)URL.revokeObjectURL(state.media.testUrl);state.media.testUrl=URL.createObjectURL(blob)}else rec='미지원'}catch{rec='실패'}finally{audio?.getTracks().forEach(x=>x.stop())}if(out)out.innerHTML=\`마이크 <b>\${mic}</b> · 카메라 <b>\${cam}</b> · 시험녹음 <b>\${rec}</b>\${state.media.testUrl?\` · <audio controls src="\${state.media.testUrl}"></audio>\`:''}\`}
async function startRecording(){if(state.media.recording)return;if(!state.meeting?.id){alert('서버 연결이 완료된 후 녹음을 시작해주세요.');return}if(!state.media.stream||state.media.mic!=='ok')await checkDevices(state.video.enabledByOption);if(state.media.mic!=='ok'){alert('마이크를 확인해주세요.');return}state.media.recording=true;state.media.startedAt=Date.now()-state.media.elapsed*1000;clearInterval(state.media.timer);state.media.timer=setInterval(()=>{state.media.elapsed=Math.floor((Date.now()-state.media.startedAt)/1000);const e=$('#recordTime');if(e)e.textContent=fmt(state.media.elapsed)},500);startSpeech();render()}
function stopRecording(){state.media.recording=false;clearInterval(state.media.timer);try{state._speech?.stop()}catch{}render()}
function startSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR||!state.meeting||!state.media.recording)return;const r=new SR();state._speech=r;r.continuous=true;r.interimResults=false;r.lang=localStorage.language||locale[state.lang];r.onresult=async e=>{for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal){const text=e.results[i][0].transcript.trim();if(text)await postCaption(text)}};r.onend=()=>{if(state.meeting&&state.media.recording)setTimeout(startSpeech,350)};try{r.start()}catch{}}
async function postCaption`,'meeting-runtime');

must(/async function endMeeting\(\)\{.*?\}\nfunction bind/s,
`async function endMeeting(){if(!state.meeting)return;if(!state.meeting.id){state.meeting=null;state.view='home';render();return}const mid=state.meeting.id;try{stopRecording();clearInterval(state.poll);clearInterval(state.signalPoll);try{state.media.stream?.getTracks().forEach(x=>x.stop());state.video._cameraStream?.getTracks().forEach(x=>x.stop());window.VoiceFlowAudioMonitor?.stop?.()}catch{}await api(\`/api/v1/meetings/\${mid}/finalize\`,{method:'POST',body:'{}'});state.meeting=null;state.view='home';render()}catch(err){alert(\`회의 종료 실패: \${err.message}\`)}}
function bind`,'meeting-finalize');

must(/\$\('#meetingStart'\)\?\.addEventListener\('click',\(\)=>startMeeting\(state\.view==='client'\?'client':'internal'\)\);/,
"$('#deviceTest')?.addEventListener('click',runDeviceTest);const meetingStartBtn=$('#meetingStart');if(meetingStartBtn)meetingStartBtn.onclick=()=>enterMeetingRoom(state.view==='client'?'client':'internal');",'device-test-bind');

must(/\$\('#quickJoin'\)\?\.addEventListener\('click',quickJoin\);/,
"const quickJoinBtn=$('#quickJoin');if(quickJoinBtn)quickJoinBtn.onclick=quickJoin;",'quick-join-bind');

must(/\$\('#micCheck'\)\?\.addEventListener\('click',async\(\)=>\{if\(!state\.media\.stream\)return startAudio\(\);const track=state\.media\.stream\.getAudioTracks\(\)\[0\];state\.media\.mic=track\?\.readyState==='live'&&track\.enabled\?'ok':'error';render\(\)\}\);/,
"$('#recordToggle')?.addEventListener('click',()=>state.media.recording?stopRecording():startRecording());$('#micCheck')?.addEventListener('click',()=>{void checkDevices(state.video.enabledByOption)});",'record-bind');

await fs.writeFile(file,s,'utf8');
console.log('VoiceFlow app.js patched for v2.5 meeting safety');
